pseudo_enum!(Internal: u8 {
	00 => MARIO,
	01 => FOX,
	02 => CAPTAIN_FALCON,
	03 => DONKEY_KONG,
	04 => KIRBY,
	05 => BOWSER,
	06 => LINK,
	07 => SHEIK,
	08 => NESS,
	09 => PEACH,
	10 => POPO,
	11 => NANA,
	12 => PIKACHU,
	13 => SAMUS,
	14 => YOSHI,
	15 => JIGGLYPUFF,
	16 => MEWTWO,
	17 => LUIGI,
	18 => MARTH,
	19 => ZELDA,
	20 => YOUNG_LINK,
	21 => DR_MARIO,
	22 => FALCO,
	23 => PICHU,
	24 => GAME_AND_WATCH,
	25 => GANONDORF,
	26 => ROY,
	27 => MASTER_HAND,
	28 => CRAZY_HAND,
	29 => WIRE_FRAME_MALE,
	30 => WIRE_FRAME_FEMALE,
	31 => GIGA_BOWSER,
	32 => SANDBAG,
});

pseudo_enum!(External: u8 {
	00 => CAPTAIN_FALCON,
	01 => DONKEY_KONG,
	02 => FOX,
	03 => GAME_AND_WATCH,
	04 => KIRBY,
	05 => BOWSER,
	06 => LINK,
	07 => LUIGI,
	08 => MARIO,
	09 => MARTH,
	10 => MEWTWO,
	11 => NESS,
	12 => PEACH,
	13 => PIKACHU,
	14 => ICE_CLIMBERS,
	15 => JIGGLYPUFF,
	16 => SAMUS,
	17 => YOSHI,
	18 => ZELDA,
	19 => SHEIK,
	20 => FALCO,
	21 => YOUNG_LINK,
	22 => DR_MARIO,
	23 => ROY,
	24 => PICHU,
	25 => GANONDORF,
	26 => MASTER_HAND,
	27 => WIRE_FRAME_MALE,
	28 => WIRE_FRAME_FEMALE,
	29 => GIGA_BOWSER,
	30 => CRAZY_HAND,
	31 => SANDBAG,
	32 => POPO,
});

impl TryFrom<External> for Internal {
	type Error = String;
	fn try_from(e: External) -> Result<Self, Self::Error> {
		Ok(match e {
			External::CAPTAIN_FALCON => Internal::CAPTAIN_FALCON,
			External::DONKEY_KONG => Internal::DONKEY_KONG,
			External::FOX => Internal::FOX,
			External::GAME_AND_WATCH => Internal::GAME_AND_WATCH,
			External::KIRBY => Internal::KIRBY,
			External::BOWSER => Internal::BOWSER,
			External::LINK => Internal::LINK,
			External::LUIGI => Internal::LUIGI,
			External::MARIO => Internal::MARIO,
			External::MARTH => Internal::MARTH,
			External::MEWTWO => Internal::MEWTWO,
			External::NESS => Internal::NESS,
			External::PEACH => Internal::PEACH,
			External::PIKACHU => Internal::PIKACHU,
			External::ICE_CLIMBERS => Internal::POPO,
			External::JIGGLYPUFF => Internal::JIGGLYPUFF,
			External::SAMUS => Internal::SAMUS,
			External::YOSHI => Internal::YOSHI,
			External::ZELDA => Internal::ZELDA,
			External::SHEIK => Internal::SHEIK,
			External::FALCO => Internal::FALCO,
			External::YOUNG_LINK => Internal::YOUNG_LINK,
			External::DR_MARIO => Internal::DR_MARIO,
			External::ROY => Internal::ROY,
			External::PICHU => Internal::PICHU,
			External::GANONDORF => Internal::GANONDORF,
			External::MASTER_HAND => Internal::MASTER_HAND,
			External::WIRE_FRAME_MALE => Internal::WIRE_FRAME_MALE,
			External::WIRE_FRAME_FEMALE => Internal::WIRE_FRAME_FEMALE,
			External::GIGA_BOWSER => Internal::GIGA_BOWSER,
			External::CRAZY_HAND => Internal::CRAZY_HAND,
			External::SANDBAG => Internal::SANDBAG,
			External::POPO => Internal::POPO,
			n => Err(format!("Unknown character: {:?}", n))?,
		})
	}
}
