// This file is auto-generated by `gen/scripts/frames`. Do not edit.

//! Immutable (fully-parsed) frame data, as Arrow arrays.
//!
//! This is what you get when you parse a game in one shot using [`crate::io::slippi::read`] or
//! [`crate::io::peppi::read`].
//!
//! These arrays can be shared, and cloning them is `O(1)`. See the
//! [arrow docs](https://docs.rs/arrow/latest/arrow/) for more.

#![allow(unused_variables)]

mod peppi;
mod slippi;

use std::fmt;

use arrow::buffer::{NullBuffer, OffsetBuffer};

use crate::{
	frame::{self, Rollbacks, transpose},
	game::Port,
	io::slippi::Version,
};

fn start_end(buf: &Option<OffsetBuffer<i32>>, i: usize) -> (usize, usize) {
	let b = buf.as_ref().unwrap();
	(b[i].try_into().unwrap(), b[i + 1].try_into().unwrap())
}

/// Frame data for a single character (ICs are two characters).
#[derive(Debug)]
pub struct Data {
	pub pre: Pre,
	pub post: Post,
	pub validity: Option<NullBuffer>,
}

impl Data {
	pub fn transpose_one(&self, i: usize, version: Version) -> Option<transpose::Data> {
		self.validity
			.as_ref()
			.map_or(true, |v| v.is_valid(i))
			.then(|| transpose::Data {
				pre: self.pre.transpose_one(i, version),
				post: self.post.transpose_one(i, version),
			})
	}
}

/// Frame data for a single port.
#[derive(Debug)]
pub struct PortData {
	pub port: Port,
	pub leader: Data,
	/// The "backup" ICs character
	pub follower: Option<Data>,
	pub validity: Option<NullBuffer>,
}

impl PortData {
	pub fn transpose_one(&self, i: usize, version: Version) -> Option<transpose::PortData> {
		self.validity
			.as_ref()
			.map_or(true, |v| v.is_valid(i))
			.then(|| transpose::PortData {
				port: self.port,
				leader: self.leader.transpose_one(i, version).unwrap(),
				follower: self
					.follower
					.as_ref()
					.and_then(|f| f.transpose_one(i, version)),
			})
	}
}

/// All frame data for a single game, in struct-of-arrays format.
pub struct Frame {
	/// Frame IDs start at `-123` and increment each frame. May repeat in case of rollbacks
	pub id: Vec<i32>,
	/// Port-specific data
	pub ports: Vec<PortData>,
	/// Start-of-frame data
	pub start: Option<Start>,
	/// End-of-frame data
	pub end: Option<End>,

	/// Item data
	pub item: Option<Item>,
	/// Logically, each frame has its own array of items. But we represent all item data in a flat array, with this field indicating the start of each sub-array
	pub item_offset: Option<OffsetBuffer<i32>>,

	pub fod_platform: Option<FodPlatform>,
	pub fod_platform_offset: Option<OffsetBuffer<i32>>,

	pub dreamland_whispy: Option<DreamlandWhispy>,
	pub dreamland_whispy_offset: Option<OffsetBuffer<i32>>,

	pub stadium_transformation: Option<StadiumTransformation>,
	pub stadium_transformation_offset: Option<OffsetBuffer<i32>>,
}

impl Frame {
	pub fn len(&self) -> usize {
		self.id.len()
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Frame {
		transpose::Frame {
			id: self.id[i],
			ports: self
				.ports
				.iter()
				.map(|p| p.transpose_one(i, version))
				.collect(),
			start: version
				.gte(2, 2)
				.then(|| self.start.as_ref().unwrap().transpose_one(i, version)),
			end: version
				.gte(3, 0)
				.then(|| self.end.as_ref().unwrap().transpose_one(i, version)),
			items: version.gte(3, 0).then(|| {
				let (start, end) = start_end(&self.item_offset, i);
				(start..end)
					.map(|i| self.item.as_ref().unwrap().transpose_one(i, version))
					.collect()
			}),
			fod_platforms: version.gte(3, 18).then(|| {
				let (start, end) = start_end(&self.fod_platform_offset, i);
				(start..end)
					.map(|i| {
						self.fod_platform
							.as_ref()
							.unwrap()
							.transpose_one(i, version)
					})
					.collect()
			}),
			dreamland_whispys: version.gte(3, 18).then(|| {
				let (start, end) = start_end(&self.dreamland_whispy_offset, i);
				(start..end)
					.map(|i| {
						self.dreamland_whispy
							.as_ref()
							.unwrap()
							.transpose_one(i, version)
					})
					.collect()
			}),
			stadium_transformations: version.gte(3, 18).then(|| {
				let (start, end) = start_end(&self.stadium_transformation_offset, i);
				(start..end)
					.map(|i| {
						self.stadium_transformation
							.as_ref()
							.unwrap()
							.transpose_one(i, version)
					})
					.collect()
			}),
		}
	}

	/// Frames IDs may appear multiple times due to rollbacks. This fn lets you
	/// "dedupe" rollbacks, by returning `true` for all but one of each unique
	/// frame ID. The value returned at index `i` corresponds to `self.id[i]`.
	pub fn rollbacks(&self, keep: Rollbacks) -> Vec<bool> {
		use Rollbacks::*;
		match keep {
			ExceptFirst => self.rollbacks_(self.id.iter().enumerate()),
			ExceptLast => self.rollbacks_(self.id.iter().enumerate().rev()),
		}
	}

	fn rollbacks_<'a>(&self, ids: impl Iterator<Item = (usize, &'a i32)>) -> Vec<bool> {
		let mut result = vec![false; self.len()];
		let unique_id_count = self.id.iter().max().map_or(0, |idx| {
			1 + usize::try_from(idx - frame::FIRST_INDEX).unwrap()
		});
		let mut seen = vec![false; unique_id_count];
		for (idx, id) in ids {
			let zero_based_id = usize::try_from(id - frame::FIRST_INDEX).unwrap();
			if !seen[zero_based_id] {
				seen[zero_based_id] = true;
				result[idx] = false;
			} else {
				result[idx] = true;
			}
		}
		result
	}
}

impl fmt::Debug for Frame {
	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> std::result::Result<(), fmt::Error> {
		write!(f, "Frame {{ len: {} }}", self.id.len())
	}
}

/// This event only occurs on Dreamland 64, and is sent whenever Whispy changes blow directions.
#[derive(Debug)]
pub struct DreamlandWhispy {
	/// Which direction Whispy is blowing (0 = None, 1 = Left, 2 = Right)
	pub direction: Vec<u8>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl DreamlandWhispy {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::DreamlandWhispy {
		transpose::DreamlandWhispy {
			direction: self.direction[i],
		}
	}
}

/// Information about the end of the game.
#[derive(Debug)]
pub struct End {
	/// *Added: v3.7* Index of the latest frame which is guaranteed not to happen again (rollback)
	pub latest_finalized_frame: Option<Vec<i32>>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl End {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::End {
		transpose::End {
			latest_finalized_frame: self.latest_finalized_frame.as_ref().map(|x| x[i]),
		}
	}
}

/// This event only occurs on Fountain of Dreams, and is sent for each change in platform height. If both platforms are moving, there will be two events per frame.
#[derive(Debug)]
pub struct FodPlatform {
	/// Which platform has moved. (0 = Right, 1 = Left)
	pub platform: Vec<u8>,
	/// The platform's new height
	pub height: Vec<f32>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl FodPlatform {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::FodPlatform {
		transpose::FodPlatform {
			platform: self.platform[i],
			height: self.height[i],
		}
	}
}

/// An active item (includes projectiles).
#[derive(Debug)]
pub struct Item {
	/// Item type
	pub r#type: Vec<u16>,
	/// Item’s action state
	pub state: Vec<u8>,
	/// Direction item is facing
	pub direction: Vec<f32>,
	/// Item’s velocity
	pub velocity: Velocity,
	/// Item’s position
	pub position: Position,
	/// Amount of damage item has taken
	pub damage: Vec<u16>,
	/// Frames remaining until item expires
	pub timer: Vec<f32>,
	/// Unique, serial ID per item spawned
	pub id: Vec<u32>,
	/// *Added: v3.2* Miscellaneous item state
	pub misc: Option<ItemMisc>,
	/// *Added: v3.6* Port that owns the item (-1 when unowned)
	pub owner: Option<Vec<i8>>,
	/// *Added: v3.16* Inherited instance ID of the owner (0 when unowned)
	pub instance_id: Option<Vec<u16>>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl Item {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Item {
		transpose::Item {
			r#type: self.r#type[i],
			state: self.state[i],
			direction: self.direction[i],
			velocity: self.velocity.transpose_one(i, version),
			position: self.position.transpose_one(i, version),
			damage: self.damage[i],
			timer: self.timer[i],
			id: self.id[i],
			misc: self.misc.as_ref().map(|x| x.transpose_one(i, version)),
			owner: self.owner.as_ref().map(|x| x[i]),
			instance_id: self.instance_id.as_ref().map(|x| x[i]),
		}
	}
}

/// Miscellaneous item state.
#[derive(Debug)]
pub struct ItemMisc(pub Vec<u8>, pub Vec<u8>, pub Vec<u8>, pub Vec<u8>);

impl ItemMisc {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::ItemMisc {
		transpose::ItemMisc(self.0[i], self.1[i], self.2[i], self.3[i])
	}
}

/// 2D position.
#[derive(Debug)]
pub struct Position {
	pub x: Vec<f32>,
	pub y: Vec<f32>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl Position {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Position {
		transpose::Position {
			x: self.x[i],
			y: self.y[i],
		}
	}
}

/// Post-frame update data, for making decisions about game states (such as computing stats).
///
/// Information is collected at the end of collision detection, which is the last consideration of the game engine.
#[derive(Debug)]
pub struct Post {
	/// In-game character (can only change for Zelda/Sheik)
	pub character: Vec<u8>,
	/// Character’s action state
	pub state: Vec<u16>,
	/// Character’s position
	pub position: Position,
	/// Direction the character is facing
	pub direction: Vec<f32>,
	/// Damage taken (percent)
	pub percent: Vec<f32>,
	/// Size/health of shield
	pub shield: Vec<f32>,
	/// Last attack ID that this character landed
	pub last_attack_landed: Vec<u8>,
	/// Combo count (as defined by the game)
	pub combo_count: Vec<u8>,
	/// Port that last hit this player. Bugged in Melee: will be set to `6` in certain situations
	pub last_hit_by: Vec<u8>,
	/// Number of stocks remaining
	pub stocks: Vec<u8>,
	/// *Added: v0.2* Number of frames action state has been active. Can have a fractional component
	pub state_age: Option<Vec<f32>>,
	/// *Added: v2.0* State flags
	pub state_flags: Option<StateFlags>,
	/// *Added: v2.0* Used for different things. While in hitstun, contains hitstun frames remaining
	pub misc_as: Option<Vec<f32>>,
	/// *Added: v2.0* Is the character airborne?
	pub airborne: Option<Vec<u8>>,
	/// *Added: v2.0* Ground ID the character last touched
	pub ground: Option<Vec<u16>>,
	/// *Added: v2.0* Number of jumps remaining
	pub jumps: Option<Vec<u8>>,
	/// *Added: v2.0* L-cancel status (0 = none, 1 = successful, 2 = unsuccessful)
	pub l_cancel: Option<Vec<u8>>,
	/// *Added: v2.1* Hurtbox state (0 = vulnerable, 1 = invulnerable, 2 = intangible)
	pub hurtbox_state: Option<Vec<u8>>,
	/// *Added: v3.5* Self-induced and knockback velocities
	pub velocities: Option<Velocities>,
	/// *Added: v3.8* Hitlag frames remaining
	pub hitlag: Option<Vec<f32>>,
	/// *Added: v3.11* Animation the character is in
	pub animation_index: Option<Vec<u32>>,
	/// *Added: v3.16* Instance ID of the player/item that last hit this player
	pub last_hit_by_instance: Option<Vec<u16>>,
	/// *Added: v3.16* Unique, serial ID for each new action state across all characters. Resets to 0 on death
	pub instance_id: Option<Vec<u16>>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl Post {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Post {
		transpose::Post {
			character: self.character[i],
			state: self.state[i],
			position: self.position.transpose_one(i, version),
			direction: self.direction[i],
			percent: self.percent[i],
			shield: self.shield[i],
			last_attack_landed: self.last_attack_landed[i],
			combo_count: self.combo_count[i],
			last_hit_by: self.last_hit_by[i],
			stocks: self.stocks[i],
			state_age: self.state_age.as_ref().map(|x| x[i]),
			state_flags: self
				.state_flags
				.as_ref()
				.map(|x| x.transpose_one(i, version)),
			misc_as: self.misc_as.as_ref().map(|x| x[i]),
			airborne: self.airborne.as_ref().map(|x| x[i]),
			ground: self.ground.as_ref().map(|x| x[i]),
			jumps: self.jumps.as_ref().map(|x| x[i]),
			l_cancel: self.l_cancel.as_ref().map(|x| x[i]),
			hurtbox_state: self.hurtbox_state.as_ref().map(|x| x[i]),
			velocities: self
				.velocities
				.as_ref()
				.map(|x| x.transpose_one(i, version)),
			hitlag: self.hitlag.as_ref().map(|x| x[i]),
			animation_index: self.animation_index.as_ref().map(|x| x[i]),
			last_hit_by_instance: self.last_hit_by_instance.as_ref().map(|x| x[i]),
			instance_id: self.instance_id.as_ref().map(|x| x[i]),
		}
	}
}

/// Pre-frame update data, required to reconstruct a replay.
///
/// Information is collected right before controller inputs are used to figure out the character’s next action.
#[derive(Debug)]
pub struct Pre {
	/// Random seed
	pub random_seed: Vec<u32>,
	/// Character’s action state
	pub state: Vec<u16>,
	/// Character’s position
	pub position: Position,
	/// Direction the character is facing
	pub direction: Vec<f32>,
	/// Processed analog joystick position
	pub joystick: Position,
	/// Processed analog c-stick position
	pub cstick: Position,
	/// Processed analog trigger position
	pub triggers: Vec<f32>,
	/// Processed button-state bitmask
	pub buttons: Vec<u32>,
	/// Physical button-state bitmask
	pub buttons_physical: Vec<u16>,
	/// Physical analog trigger positions (useful for IPM)
	pub triggers_physical: TriggersPhysical,
	/// *Added: v1.2* Raw joystick x-position
	pub raw_analog_x: Option<Vec<i8>>,
	/// *Added: v1.4* Damage taken (percent)
	pub percent: Option<Vec<f32>>,
	/// *Added: v3.15* Raw joystick y-position
	pub raw_analog_y: Option<Vec<i8>>,
	/// *Added: v3.17* Raw c-stick x-position
	pub raw_analog_cstick_x: Option<Vec<i8>>,
	/// *Added: v3.17* Raw c-stick y-position
	pub raw_analog_cstick_y: Option<Vec<i8>>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl Pre {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Pre {
		transpose::Pre {
			random_seed: self.random_seed[i],
			state: self.state[i],
			position: self.position.transpose_one(i, version),
			direction: self.direction[i],
			joystick: self.joystick.transpose_one(i, version),
			cstick: self.cstick.transpose_one(i, version),
			triggers: self.triggers[i],
			buttons: self.buttons[i],
			buttons_physical: self.buttons_physical[i],
			triggers_physical: self.triggers_physical.transpose_one(i, version),
			raw_analog_x: self.raw_analog_x.as_ref().map(|x| x[i]),
			percent: self.percent.as_ref().map(|x| x[i]),
			raw_analog_y: self.raw_analog_y.as_ref().map(|x| x[i]),
			raw_analog_cstick_x: self.raw_analog_cstick_x.as_ref().map(|x| x[i]),
			raw_analog_cstick_y: self.raw_analog_cstick_y.as_ref().map(|x| x[i]),
		}
	}
}

/// This event only occurs on Pokemon Stadium, and is sent whenever the transformation event or transformation type changes.
#[derive(Debug)]
pub struct StadiumTransformation {
	/// The subevent for each transformation. (2 = Initialize, 3 = On monitor, 4 = Previous transformation receding, 5 = New transformation rising, 6 = Finalize, 0 = Finished)
	pub event: Vec<u16>,
	/// The current or upcoming transformation. (3 = Fire, 4 = Grass, 5 = Normal, 6 = Rock, 9 = Water)
	pub r#type: Vec<u16>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl StadiumTransformation {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::StadiumTransformation {
		transpose::StadiumTransformation {
			event: self.event[i],
			r#type: self.r#type[i],
		}
	}
}

/// Initialization data such as game mode, settings, characters & stage.
#[derive(Debug)]
pub struct Start {
	/// Random seed
	pub random_seed: Vec<u32>,
	/// *Added: v3.10* Scene frame counter. Starts at 0, and increments every frame (even when paused)
	pub scene_frame_counter: Option<Vec<u32>>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl Start {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Start {
		transpose::Start {
			random_seed: self.random_seed[i],
			scene_frame_counter: self.scene_frame_counter.as_ref().map(|x| x[i]),
		}
	}
}

/// Miscellaneous state flags.
#[derive(Debug)]
pub struct StateFlags(
	pub Vec<u8>,
	pub Vec<u8>,
	pub Vec<u8>,
	pub Vec<u8>,
	pub Vec<u8>,
);

impl StateFlags {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::StateFlags {
		transpose::StateFlags(self.0[i], self.1[i], self.2[i], self.3[i], self.4[i])
	}
}

/// Trigger state.
#[derive(Debug)]
pub struct TriggersPhysical {
	pub l: Vec<f32>,
	pub r: Vec<f32>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl TriggersPhysical {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::TriggersPhysical {
		transpose::TriggersPhysical {
			l: self.l[i],
			r: self.r[i],
		}
	}
}

/// Self-induced and knockback velocities.
#[derive(Debug)]
pub struct Velocities {
	/// Self-induced x-velocity (airborne)
	pub self_x_air: Vec<f32>,
	/// Self-induced y-velocity
	pub self_y: Vec<f32>,
	/// Knockback-induced x-velocity
	pub knockback_x: Vec<f32>,
	/// Knockback-induced y-velocity
	pub knockback_y: Vec<f32>,
	/// Self-induced x-velocity (grounded)
	pub self_x_ground: Vec<f32>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl Velocities {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Velocities {
		transpose::Velocities {
			self_x_air: self.self_x_air[i],
			self_y: self.self_y[i],
			knockback_x: self.knockback_x[i],
			knockback_y: self.knockback_y[i],
			self_x_ground: self.self_x_ground[i],
		}
	}
}

/// 2D velocity.
#[derive(Debug)]
pub struct Velocity {
	pub x: Vec<f32>,
	pub y: Vec<f32>,
	/// Indicates which indexes are valid (`None` means "all valid"). Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: Option<NullBuffer>,
}

impl Velocity {
	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Velocity {
		transpose::Velocity {
			x: self.x[i],
			y: self.y[i],
		}
	}
}
