// This file is auto-generated by `gen/scripts/frames`. Do not edit.

#![allow(unused_variables)]

use crate::{
	frame::{
		PortOccupancy,
		immutable::{Data, Frame, PortData, Validity},
	},
	game::{NUM_PORTS, Port},
	io::slippi::Version,
};

use arrow::{
	array::{Array, ArrayRef, ListArray, PrimitiveArray, StructArray, downcast_array},
	buffer::{NullBuffer, OffsetBuffer, ScalarBuffer},
	datatypes::{
		DataType, Field, Fields, Float32Type, Int8Type, Int32Type, UInt8Type, UInt16Type,
		UInt32Type,
	},
};

use std::sync::Arc;

trait StructArrayConvertible {
	fn fields(version: Version) -> Fields;
	fn into_struct_array(self, version: Version) -> StructArray;
	fn from_struct_array(array: StructArray, version: Version) -> Self;

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}
}

impl From<Option<NullBuffer>> for Validity {
	fn from(nullbuf: Option<NullBuffer>) -> Validity {
		let mut validity = Validity::with_capacity(nullbuf.as_ref().map_or(0, |v| v.len()));
		if let Some(nullbuf) = nullbuf.as_ref() {
			for value in nullbuf.iter() {
				validity.push(value);
			}
		}
		validity
	}
}

impl From<Validity> for Option<NullBuffer> {
	fn from(validity: Validity) -> Option<NullBuffer> {
		if validity.values.capacity() > 0 {
			Some(NullBuffer::from(validity.values))
		} else {
			None
		}
	}
}

impl StructArrayConvertible for Data {
	fn fields(version: Version) -> Fields {
		Fields::from(vec![
			Field::new("pre", Pre::data_type(version).clone(), false),
			Field::new("post", Post::data_type(version).clone(), false),
		])
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let values = vec![
			Arc::new(self.pre.into_struct_array(version)) as ArrayRef,
			Arc::new(self.post.into_struct_array(version)) as ArrayRef,
		];
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			pre: Pre::from_struct_array(
				values[0]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			post: Post::from_struct_array(
				values[1]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			validity: validity.into(),
		}
	}
}

impl PortData {
	fn fields(version: Version, port: PortOccupancy) -> Fields {
		let mut fields = vec![Field::new(
			"leader",
			Data::data_type(version).clone(),
			false,
		)];
		if port.follower {
			fields.push(Field::new(
				"follower",
				Data::data_type(version).clone(),
				true,
			));
		}
		Fields::from(fields)
	}

	fn data_type(version: Version, port: PortOccupancy) -> DataType {
		DataType::Struct(Self::fields(version, port))
	}

	fn into_struct_array(self, version: Version, port: PortOccupancy) -> StructArray {
		let mut values = vec![Arc::new(self.leader.into_struct_array(version)) as ArrayRef];
		if let Some(follower) = self.follower {
			values.push(Arc::new(follower.into_struct_array(version)) as ArrayRef);
		}
		StructArray::new(Self::fields(version, port), values, None)
	}

	fn from_struct_array(array: StructArray, version: Version, port: Port) -> Self {
		let (fields, values, validity) = array.into_parts();
		assert_eq!("leader", fields[0].name());
		fields.get(1).map(|f| assert_eq!("follower", f.name()));
		Self {
			port: port,
			leader: Data::from_struct_array(
				values[0]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			follower: values.get(1).map(|x| {
				Data::from_struct_array(
					x.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			validity: validity.into(),
		}
	}
}

impl Frame {
	fn port_fields(version: Version, ports: &[PortOccupancy]) -> Fields {
		Fields::from(
			ports
				.iter()
				.map(|p| {
					Field::new(
						format!("{}", p.port),
						PortData::data_type(version, *p).clone(),
						true,
					)
				})
				.collect::<Vec<_>>(),
		)
	}

	fn item_field(version: Version) -> Arc<Field> {
		Arc::new(Field::new("item", Item::data_type(version), false))
	}

	fn fod_platform_field(version: Version) -> Arc<Field> {
		Arc::new(Field::new(
			"fod_platform",
			FodPlatform::data_type(version),
			false,
		))
	}

	fn dreamland_whispy_field(version: Version) -> Arc<Field> {
		Arc::new(Field::new(
			"dreamland_whispy",
			DreamlandWhispy::data_type(version),
			false,
		))
	}

	fn stadium_transformation_field(version: Version) -> Arc<Field> {
		Arc::new(Field::new(
			"stadium_transformation",
			StadiumTransformation::data_type(version),
			false,
		))
	}

	fn fields(version: Version, ports: &[PortOccupancy]) -> Fields {
		let mut fields = vec![
			Field::new("id", DataType::Int32, false),
			Field::new(
				"ports",
				DataType::Struct(Self::port_fields(version, ports)),
				false,
			),
		];
		if version.gte(2, 2) {
			fields.push(Field::new(
				"start",
				Start::data_type(version).clone(),
				false,
			));
			if version.gte(3, 0) {
				fields.push(Field::new("end", End::data_type(version).clone(), false));
				fields.push(Field::new(
					"item",
					DataType::List(Self::item_field(version)),
					false,
				));
				if version.gte(3, 18) {
					fields.push(Field::new(
						"fod_platform",
						DataType::List(Self::fod_platform_field(version)),
						false,
					));
					fields.push(Field::new(
						"dreamland_whispy",
						DataType::List(Self::dreamland_whispy_field(version)),
						false,
					));
					fields.push(Field::new(
						"stadium_transformation",
						DataType::List(Self::stadium_transformation_field(version)),
						false,
					));
				}
			}
		}
		Fields::from(fields)
	}

	pub fn into_struct_array(self, version: Version, ports: &[PortOccupancy]) -> StructArray {
		let values: Vec<_> = std::iter::zip(ports, self.ports)
			.map(|(occupancy, data)| {
				Arc::new(data.into_struct_array(version, *occupancy)) as ArrayRef
			})
			.collect();

		let mut arrays = vec![
			Arc::new(PrimitiveArray::<Int32Type>::from(self.id)) as ArrayRef,
			Arc::new(StructArray::new(
				Self::port_fields(version, ports),
				values,
				None,
			)) as ArrayRef,
		];

		if version.gte(2, 2) {
			arrays.push(Arc::new(self.start.unwrap().into_struct_array(version)));
			if version.gte(3, 0) {
				arrays.push(Arc::new(self.end.unwrap().into_struct_array(version)));
				let item_values = Arc::new(self.item.unwrap().into_struct_array(version));
				arrays.push(Arc::new(ListArray::new(
					Self::item_field(version),
					OffsetBuffer::new(ScalarBuffer::from(self.item_offset.unwrap())),
					item_values,
					None,
				)) as ArrayRef);
				if version.gte(3, 18) {
					let fod_platform_values =
						Arc::new(self.fod_platform.unwrap().into_struct_array(version));
					arrays.push(Arc::new(ListArray::new(
						Self::fod_platform_field(version),
						OffsetBuffer::new(ScalarBuffer::from(self.fod_platform_offset.unwrap())),
						fod_platform_values,
						None,
					)) as ArrayRef);
					let dreamland_whispy_values =
						Arc::new(self.dreamland_whispy.unwrap().into_struct_array(version));
					arrays.push(Arc::new(ListArray::new(
						Self::dreamland_whispy_field(version),
						OffsetBuffer::new(ScalarBuffer::from(
							self.dreamland_whispy_offset.unwrap(),
						)),
						dreamland_whispy_values,
						None,
					)) as ArrayRef);
					let stadium_transformation_values = Arc::new(
						self.stadium_transformation
							.unwrap()
							.into_struct_array(version),
					);
					arrays.push(Arc::new(ListArray::new(
						Self::stadium_transformation_field(version),
						OffsetBuffer::new(ScalarBuffer::from(
							self.stadium_transformation_offset.unwrap(),
						)),
						stadium_transformation_values,
						None,
					)) as ArrayRef);
				}
			}
		}

		StructArray::new(Self::fields(version, ports), arrays, None)
	}

	fn port_data_from_struct_array(array: StructArray, version: Version) -> Vec<PortData> {
		let (fields, values, _) = array.into_parts();
		let mut ports = vec![];
		for i in 0..NUM_PORTS {
			if let Some(a) = values.get(i as usize) {
				ports.push(PortData::from_struct_array(
					a.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
					Port::parse(&fields[i as usize].name()).unwrap(),
				));
			}
		}
		ports
	}

	fn values_and_offsets<T: StructArrayConvertible>(
		arr: &Arc<dyn Array>,
		version: Version,
	) -> (Option<T>, Option<OffsetBuffer<i32>>) {
		println!("arr offset: {}", arr.offset());
		let list_array = downcast_array::<ListArray>(arr);
		println!("list_array offset: {}", list_array.offset());
		let (_, offsets, values, _) = list_array.into_parts();
		println!("ptr_offset 1: {}", offsets.inner().inner().ptr_offset());
		let values = T::from_struct_array(downcast_array::<StructArray>(&values), version);
		(Some(values), Some(offsets))
	}

	pub fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (fields, values, _) = array.into_parts();
		println!("id offset: {}", values[0].offset());
		assert_eq!("id", fields[0].name());
		assert_eq!("ports", fields[1].name());
		if version.gte(2, 2) {
			assert_eq!("start", fields[2].name());
			if version.gte(3, 0) {
				assert_eq!("end", fields[3].name());
				assert_eq!("item", fields[4].name());
				if version.gte(3, 18) {
					assert_eq!("fod_platform", fields[5].name());
					assert_eq!("dreamland_whispy", fields[6].name());
					assert_eq!("stadium_transformation", fields[7].name());
				}
			}
		}

		let (item, item_offset) = values
			.get(4)
			.map_or((None, None), |arr| Frame::values_and_offsets(arr, version));
		let (fod_platform, fod_platform_offset) = values
			.get(5)
			.map_or((None, None), |arr| Frame::values_and_offsets(arr, version));
		let (dreamland_whispy, dreamland_whispy_offset) = values
			.get(6)
			.map_or((None, None), |arr| Frame::values_and_offsets(arr, version));
		let (stadium_transformation, stadium_transformation_offset) = values
			.get(7)
			.map_or((None, None), |arr| Frame::values_and_offsets(arr, version));

		Self {
			id: downcast_array::<PrimitiveArray<Int32Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			ports: Self::port_data_from_struct_array(
				values[1]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			start: values.get(2).map(|v| {
				Start::from_struct_array(
					v.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			end: values.get(3).map(|v| {
				End::from_struct_array(
					v.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			item,
			item_offset: item_offset // FIXME: avoid clone
				.map(|buf| buf.into_inner().into_inner().typed_data().into()),
			fod_platform,
			fod_platform_offset: fod_platform_offset
				.map(|buf| buf.into_inner().into_inner().typed_data().into()),
			dreamland_whispy,
			dreamland_whispy_offset: dreamland_whispy_offset
				.map(|buf| buf.into_inner().into_inner().typed_data().into()),
			stadium_transformation,
			stadium_transformation_offset: stadium_transformation_offset
				.map(|buf| buf.into_inner().into_inner().typed_data().into()),
		}
	}
}

use crate::frame::immutable::DreamlandWhispy;

impl StructArrayConvertible for DreamlandWhispy {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("direction", DataType::UInt8, false))
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.direction)) as ArrayRef);
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			direction: downcast_array::<PrimitiveArray<UInt8Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::End;

impl StructArrayConvertible for End {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			if version.gte(3, 7) {
				fields.push(Field::new("latest_finalized_frame", DataType::Int32, false))
			}
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		if version.gte(3, 7) {
			values.push(Arc::new(PrimitiveArray::<Int32Type>::from(
				self.latest_finalized_frame.unwrap(),
			)) as ArrayRef)
		};
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			latest_finalized_frame: values.get(0).map(|x| {
				downcast_array::<PrimitiveArray<Int32Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::FodPlatform;

impl StructArrayConvertible for FodPlatform {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("platform", DataType::UInt8, false));
			fields.push(Field::new("height", DataType::Float32, false))
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.platform)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.height)) as ArrayRef);
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			platform: downcast_array::<PrimitiveArray<UInt8Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			height: downcast_array::<PrimitiveArray<Float32Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::Item;

impl StructArrayConvertible for Item {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("type", DataType::UInt16, false));
			fields.push(Field::new("state", DataType::UInt8, false));
			fields.push(Field::new("direction", DataType::Float32, false));
			fields.push(Field::new("velocity", Velocity::data_type(version), false));
			fields.push(Field::new("position", Position::data_type(version), false));
			fields.push(Field::new("damage", DataType::UInt16, false));
			fields.push(Field::new("timer", DataType::Float32, false));
			fields.push(Field::new("id", DataType::UInt32, false));
			if version.gte(3, 2) {
				fields.push(Field::new("misc", ItemMisc::data_type(version), false));
				if version.gte(3, 6) {
					fields.push(Field::new("owner", DataType::Int8, false));
					if version.gte(3, 16) {
						fields.push(Field::new("instance_id", DataType::UInt16, false))
					}
				}
			}
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<UInt16Type>::from(self.r#type)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.state)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.direction)) as ArrayRef);
		values.push(Arc::new(self.velocity.into_struct_array(version)) as ArrayRef);
		values.push(Arc::new(self.position.into_struct_array(version)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt16Type>::from(self.damage)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.timer)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt32Type>::from(self.id)) as ArrayRef);
		if version.gte(3, 2) {
			values.push(Arc::new(self.misc.unwrap().into_struct_array(version)) as ArrayRef);
			if version.gte(3, 6) {
				values.push(
					Arc::new(PrimitiveArray::<Int8Type>::from(self.owner.unwrap())) as ArrayRef,
				);
				if version.gte(3, 16) {
					values.push(Arc::new(PrimitiveArray::<UInt16Type>::from(
						self.instance_id.unwrap(),
					)) as ArrayRef)
				}
			}
		};
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			r#type: downcast_array::<PrimitiveArray<UInt16Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			state: downcast_array::<PrimitiveArray<UInt8Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			direction: downcast_array::<PrimitiveArray<Float32Type>>(values[2].as_ref())
				.into_parts()
				.1
				.into(),
			velocity: Velocity::from_struct_array(
				values[3]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			position: Position::from_struct_array(
				values[4]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			damage: downcast_array::<PrimitiveArray<UInt16Type>>(values[5].as_ref())
				.into_parts()
				.1
				.into(),
			timer: downcast_array::<PrimitiveArray<Float32Type>>(values[6].as_ref())
				.into_parts()
				.1
				.into(),
			id: downcast_array::<PrimitiveArray<UInt32Type>>(values[7].as_ref())
				.into_parts()
				.1
				.into(),
			misc: values.get(8).map(|x| {
				ItemMisc::from_struct_array(
					x.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			owner: values.get(9).map(|x| {
				downcast_array::<PrimitiveArray<Int8Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			instance_id: values.get(10).map(|x| {
				downcast_array::<PrimitiveArray<UInt16Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::ItemMisc;

impl StructArrayConvertible for ItemMisc {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("0", DataType::UInt8, false));
			fields.push(Field::new("1", DataType::UInt8, false));
			fields.push(Field::new("2", DataType::UInt8, false));
			fields.push(Field::new("3", DataType::UInt8, false))
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.0)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.1)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.2)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.3)) as ArrayRef);
		StructArray::new(Self::fields(version), values, None)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self(
			downcast_array::<PrimitiveArray<UInt8Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			downcast_array::<PrimitiveArray<UInt8Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			downcast_array::<PrimitiveArray<UInt8Type>>(values[2].as_ref())
				.into_parts()
				.1
				.into(),
			downcast_array::<PrimitiveArray<UInt8Type>>(values[3].as_ref())
				.into_parts()
				.1
				.into(),
		)
	}
}

use crate::frame::immutable::Position;

impl StructArrayConvertible for Position {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("x", DataType::Float32, false));
			fields.push(Field::new("y", DataType::Float32, false))
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.x)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.y)) as ArrayRef);
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			x: downcast_array::<PrimitiveArray<Float32Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			y: downcast_array::<PrimitiveArray<Float32Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::Post;

impl StructArrayConvertible for Post {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("character", DataType::UInt8, false));
			fields.push(Field::new("state", DataType::UInt16, false));
			fields.push(Field::new("position", Position::data_type(version), false));
			fields.push(Field::new("direction", DataType::Float32, false));
			fields.push(Field::new("percent", DataType::Float32, false));
			fields.push(Field::new("shield", DataType::Float32, false));
			fields.push(Field::new("last_attack_landed", DataType::UInt8, false));
			fields.push(Field::new("combo_count", DataType::UInt8, false));
			fields.push(Field::new("last_hit_by", DataType::UInt8, false));
			fields.push(Field::new("stocks", DataType::UInt8, false));
			if version.gte(0, 2) {
				fields.push(Field::new("state_age", DataType::Float32, false));
				if version.gte(2, 0) {
					fields.push(Field::new(
						"state_flags",
						StateFlags::data_type(version),
						false,
					));
					fields.push(Field::new("misc_as", DataType::Float32, false));
					fields.push(Field::new("airborne", DataType::UInt8, false));
					fields.push(Field::new("ground", DataType::UInt16, false));
					fields.push(Field::new("jumps", DataType::UInt8, false));
					fields.push(Field::new("l_cancel", DataType::UInt8, false));
					if version.gte(2, 1) {
						fields.push(Field::new("hurtbox_state", DataType::UInt8, false));
						if version.gte(3, 5) {
							fields.push(Field::new(
								"velocities",
								Velocities::data_type(version),
								false,
							));
							if version.gte(3, 8) {
								fields.push(Field::new("hitlag", DataType::Float32, false));
								if version.gte(3, 11) {
									fields.push(Field::new(
										"animation_index",
										DataType::UInt32,
										false,
									));
									if version.gte(3, 16) {
										fields.push(Field::new(
											"last_hit_by_instance",
											DataType::UInt16,
											false,
										));
										fields.push(Field::new(
											"instance_id",
											DataType::UInt16,
											false,
										))
									}
								}
							}
						}
					}
				}
			}
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.character)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt16Type>::from(self.state)) as ArrayRef);
		values.push(Arc::new(self.position.into_struct_array(version)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.direction)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.percent)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.shield)) as ArrayRef);
		values
			.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.last_attack_landed)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.combo_count)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.last_hit_by)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.stocks)) as ArrayRef);
		if version.gte(0, 2) {
			values.push(
				Arc::new(PrimitiveArray::<Float32Type>::from(self.state_age.unwrap())) as ArrayRef,
			);
			if version.gte(2, 0) {
				values.push(
					Arc::new(self.state_flags.unwrap().into_struct_array(version)) as ArrayRef,
				);
				values.push(
					Arc::new(PrimitiveArray::<Float32Type>::from(self.misc_as.unwrap()))
						as ArrayRef,
				);
				values.push(
					Arc::new(PrimitiveArray::<UInt8Type>::from(self.airborne.unwrap())) as ArrayRef,
				);
				values.push(
					Arc::new(PrimitiveArray::<UInt16Type>::from(self.ground.unwrap())) as ArrayRef,
				);
				values.push(
					Arc::new(PrimitiveArray::<UInt8Type>::from(self.jumps.unwrap())) as ArrayRef,
				);
				values.push(
					Arc::new(PrimitiveArray::<UInt8Type>::from(self.l_cancel.unwrap())) as ArrayRef,
				);
				if version.gte(2, 1) {
					values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(
						self.hurtbox_state.unwrap(),
					)) as ArrayRef);
					if version.gte(3, 5) {
						values.push(
							Arc::new(self.velocities.unwrap().into_struct_array(version))
								as ArrayRef,
						);
						if version.gte(3, 8) {
							values.push(Arc::new(PrimitiveArray::<Float32Type>::from(
								self.hitlag.unwrap(),
							)) as ArrayRef);
							if version.gte(3, 11) {
								values.push(Arc::new(PrimitiveArray::<UInt32Type>::from(
									self.animation_index.unwrap(),
								)) as ArrayRef);
								if version.gte(3, 16) {
									values.push(Arc::new(PrimitiveArray::<UInt16Type>::from(
										self.last_hit_by_instance.unwrap(),
									)) as ArrayRef);
									values.push(Arc::new(PrimitiveArray::<UInt16Type>::from(
										self.instance_id.unwrap(),
									)) as ArrayRef)
								}
							}
						}
					}
				}
			}
		};
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			character: downcast_array::<PrimitiveArray<UInt8Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			state: downcast_array::<PrimitiveArray<UInt16Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			position: Position::from_struct_array(
				values[2]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			direction: downcast_array::<PrimitiveArray<Float32Type>>(values[3].as_ref())
				.into_parts()
				.1
				.into(),
			percent: downcast_array::<PrimitiveArray<Float32Type>>(values[4].as_ref())
				.into_parts()
				.1
				.into(),
			shield: downcast_array::<PrimitiveArray<Float32Type>>(values[5].as_ref())
				.into_parts()
				.1
				.into(),
			last_attack_landed: downcast_array::<PrimitiveArray<UInt8Type>>(values[6].as_ref())
				.into_parts()
				.1
				.into(),
			combo_count: downcast_array::<PrimitiveArray<UInt8Type>>(values[7].as_ref())
				.into_parts()
				.1
				.into(),
			last_hit_by: downcast_array::<PrimitiveArray<UInt8Type>>(values[8].as_ref())
				.into_parts()
				.1
				.into(),
			stocks: downcast_array::<PrimitiveArray<UInt8Type>>(values[9].as_ref())
				.into_parts()
				.1
				.into(),
			state_age: values.get(10).map(|x| {
				downcast_array::<PrimitiveArray<Float32Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			state_flags: values.get(11).map(|x| {
				StateFlags::from_struct_array(
					x.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			misc_as: values.get(12).map(|x| {
				downcast_array::<PrimitiveArray<Float32Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			airborne: values.get(13).map(|x| {
				downcast_array::<PrimitiveArray<UInt8Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			ground: values.get(14).map(|x| {
				downcast_array::<PrimitiveArray<UInt16Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			jumps: values.get(15).map(|x| {
				downcast_array::<PrimitiveArray<UInt8Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			l_cancel: values.get(16).map(|x| {
				downcast_array::<PrimitiveArray<UInt8Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			hurtbox_state: values.get(17).map(|x| {
				downcast_array::<PrimitiveArray<UInt8Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			velocities: values.get(18).map(|x| {
				Velocities::from_struct_array(
					x.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			hitlag: values.get(19).map(|x| {
				downcast_array::<PrimitiveArray<Float32Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			animation_index: values.get(20).map(|x| {
				downcast_array::<PrimitiveArray<UInt32Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			last_hit_by_instance: values.get(21).map(|x| {
				downcast_array::<PrimitiveArray<UInt16Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			instance_id: values.get(22).map(|x| {
				downcast_array::<PrimitiveArray<UInt16Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::Pre;

impl StructArrayConvertible for Pre {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("random_seed", DataType::UInt32, false));
			fields.push(Field::new("state", DataType::UInt16, false));
			fields.push(Field::new("position", Position::data_type(version), false));
			fields.push(Field::new("direction", DataType::Float32, false));
			fields.push(Field::new("joystick", Position::data_type(version), false));
			fields.push(Field::new("cstick", Position::data_type(version), false));
			fields.push(Field::new("triggers", DataType::Float32, false));
			fields.push(Field::new("buttons", DataType::UInt32, false));
			fields.push(Field::new("buttons_physical", DataType::UInt16, false));
			fields.push(Field::new(
				"triggers_physical",
				TriggersPhysical::data_type(version),
				false,
			));
			if version.gte(1, 2) {
				fields.push(Field::new("raw_analog_x", DataType::Int8, false));
				if version.gte(1, 4) {
					fields.push(Field::new("percent", DataType::Float32, false));
					if version.gte(3, 15) {
						fields.push(Field::new("raw_analog_y", DataType::Int8, false));
						if version.gte(3, 17) {
							fields.push(Field::new("raw_analog_cstick_x", DataType::Int8, false));
							fields.push(Field::new("raw_analog_cstick_y", DataType::Int8, false))
						}
					}
				}
			}
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<UInt32Type>::from(self.random_seed)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt16Type>::from(self.state)) as ArrayRef);
		values.push(Arc::new(self.position.into_struct_array(version)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.direction)) as ArrayRef);
		values.push(Arc::new(self.joystick.into_struct_array(version)) as ArrayRef);
		values.push(Arc::new(self.cstick.into_struct_array(version)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.triggers)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt32Type>::from(self.buttons)) as ArrayRef);
		values
			.push(Arc::new(PrimitiveArray::<UInt16Type>::from(self.buttons_physical)) as ArrayRef);
		values.push(Arc::new(self.triggers_physical.into_struct_array(version)) as ArrayRef);
		if version.gte(1, 2) {
			values.push(
				Arc::new(PrimitiveArray::<Int8Type>::from(self.raw_analog_x.unwrap())) as ArrayRef,
			);
			if version.gte(1, 4) {
				values.push(
					Arc::new(PrimitiveArray::<Float32Type>::from(self.percent.unwrap()))
						as ArrayRef,
				);
				if version.gte(3, 15) {
					values.push(Arc::new(PrimitiveArray::<Int8Type>::from(
						self.raw_analog_y.unwrap(),
					)) as ArrayRef);
					if version.gte(3, 17) {
						values.push(Arc::new(PrimitiveArray::<Int8Type>::from(
							self.raw_analog_cstick_x.unwrap(),
						)) as ArrayRef);
						values.push(Arc::new(PrimitiveArray::<Int8Type>::from(
							self.raw_analog_cstick_y.unwrap(),
						)) as ArrayRef)
					}
				}
			}
		};
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			random_seed: downcast_array::<PrimitiveArray<UInt32Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			state: downcast_array::<PrimitiveArray<UInt16Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			position: Position::from_struct_array(
				values[2]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			direction: downcast_array::<PrimitiveArray<Float32Type>>(values[3].as_ref())
				.into_parts()
				.1
				.into(),
			joystick: Position::from_struct_array(
				values[4]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			cstick: Position::from_struct_array(
				values[5]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			triggers: downcast_array::<PrimitiveArray<Float32Type>>(values[6].as_ref())
				.into_parts()
				.1
				.into(),
			buttons: downcast_array::<PrimitiveArray<UInt32Type>>(values[7].as_ref())
				.into_parts()
				.1
				.into(),
			buttons_physical: downcast_array::<PrimitiveArray<UInt16Type>>(values[8].as_ref())
				.into_parts()
				.1
				.into(),
			triggers_physical: TriggersPhysical::from_struct_array(
				values[9]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			raw_analog_x: values.get(10).map(|x| {
				downcast_array::<PrimitiveArray<Int8Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			percent: values.get(11).map(|x| {
				downcast_array::<PrimitiveArray<Float32Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			raw_analog_y: values.get(12).map(|x| {
				downcast_array::<PrimitiveArray<Int8Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			raw_analog_cstick_x: values.get(13).map(|x| {
				downcast_array::<PrimitiveArray<Int8Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			raw_analog_cstick_y: values.get(14).map(|x| {
				downcast_array::<PrimitiveArray<Int8Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::StadiumTransformation;

impl StructArrayConvertible for StadiumTransformation {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("event", DataType::UInt16, false));
			fields.push(Field::new("type", DataType::UInt16, false))
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<UInt16Type>::from(self.event)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt16Type>::from(self.r#type)) as ArrayRef);
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			event: downcast_array::<PrimitiveArray<UInt16Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			r#type: downcast_array::<PrimitiveArray<UInt16Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::Start;

impl StructArrayConvertible for Start {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("random_seed", DataType::UInt32, false));
			if version.gte(3, 10) {
				fields.push(Field::new("scene_frame_counter", DataType::UInt32, false))
			}
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<UInt32Type>::from(self.random_seed)) as ArrayRef);
		if version.gte(3, 10) {
			values.push(Arc::new(PrimitiveArray::<UInt32Type>::from(
				self.scene_frame_counter.unwrap(),
			)) as ArrayRef)
		};
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			random_seed: downcast_array::<PrimitiveArray<UInt32Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			scene_frame_counter: values.get(1).map(|x| {
				downcast_array::<PrimitiveArray<UInt32Type>>(x.as_ref())
					.into_parts()
					.1
					.into()
			}),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::StateFlags;

impl StructArrayConvertible for StateFlags {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("0", DataType::UInt8, false));
			fields.push(Field::new("1", DataType::UInt8, false));
			fields.push(Field::new("2", DataType::UInt8, false));
			fields.push(Field::new("3", DataType::UInt8, false));
			fields.push(Field::new("4", DataType::UInt8, false))
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.0)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.1)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.2)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.3)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<UInt8Type>::from(self.4)) as ArrayRef);
		StructArray::new(Self::fields(version), values, None)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self(
			downcast_array::<PrimitiveArray<UInt8Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			downcast_array::<PrimitiveArray<UInt8Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			downcast_array::<PrimitiveArray<UInt8Type>>(values[2].as_ref())
				.into_parts()
				.1
				.into(),
			downcast_array::<PrimitiveArray<UInt8Type>>(values[3].as_ref())
				.into_parts()
				.1
				.into(),
			downcast_array::<PrimitiveArray<UInt8Type>>(values[4].as_ref())
				.into_parts()
				.1
				.into(),
		)
	}
}

use crate::frame::immutable::TriggersPhysical;

impl StructArrayConvertible for TriggersPhysical {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("l", DataType::Float32, false));
			fields.push(Field::new("r", DataType::Float32, false))
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.l)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.r)) as ArrayRef);
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			l: downcast_array::<PrimitiveArray<Float32Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			r: downcast_array::<PrimitiveArray<Float32Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::Velocities;

impl StructArrayConvertible for Velocities {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("self_x_air", DataType::Float32, false));
			fields.push(Field::new("self_y", DataType::Float32, false));
			fields.push(Field::new("knockback_x", DataType::Float32, false));
			fields.push(Field::new("knockback_y", DataType::Float32, false));
			fields.push(Field::new("self_x_ground", DataType::Float32, false))
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.self_x_air)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.self_y)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.knockback_x)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.knockback_y)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.self_x_ground)) as ArrayRef);
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			self_x_air: downcast_array::<PrimitiveArray<Float32Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			self_y: downcast_array::<PrimitiveArray<Float32Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			knockback_x: downcast_array::<PrimitiveArray<Float32Type>>(values[2].as_ref())
				.into_parts()
				.1
				.into(),
			knockback_y: downcast_array::<PrimitiveArray<Float32Type>>(values[3].as_ref())
				.into_parts()
				.1
				.into(),
			self_x_ground: downcast_array::<PrimitiveArray<Float32Type>>(values[4].as_ref())
				.into_parts()
				.1
				.into(),
			validity: validity.into(),
		}
	}
}

use crate::frame::immutable::Velocity;

impl StructArrayConvertible for Velocity {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("x", DataType::Float32, false));
			fields.push(Field::new("y", DataType::Float32, false))
		};
		Fields::from(fields)
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.x)) as ArrayRef);
		values.push(Arc::new(PrimitiveArray::<Float32Type>::from(self.y)) as ArrayRef);
		StructArray::new(Self::fields(version), values, self.validity.into())
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			x: downcast_array::<PrimitiveArray<Float32Type>>(values[0].as_ref())
				.into_parts()
				.1
				.into(),
			y: downcast_array::<PrimitiveArray<Float32Type>>(values[1].as_ref())
				.into_parts()
				.1
				.into(),
			validity: validity.into(),
		}
	}
}
