// This file is auto-generated by `gen/scripts/frames`. Do not edit.

#![allow(unused_variables)]

use std::sync::Arc;

use arrow::{
	array::{
		types::{Float32Type, Int32Type, Int8Type, UInt16Type, UInt32Type, UInt8Type},
		Array, ArrayRef, ListArray, PrimitiveArray, StructArray,
	},
	datatypes::{DataType, Field, Fields},
};

use crate::{
	frame::{
		immutable::{Data, Frame, PortData},
		PortOccupancy,
	},
	game::{Port, NUM_PORTS},
	io::slippi::Version,
};

impl Data {
	fn fields(version: Version) -> Fields {
		Fields::from(vec![
			Field::new("pre", Pre::data_type(version).clone(), false),
			Field::new("post", Post::data_type(version).clone(), false),
		])
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let values = vec![
			Arc::new(self.pre.into_struct_array(version)) as ArrayRef,
			Arc::new(self.post.into_struct_array(version)) as ArrayRef,
		];
		StructArray::new(Self::fields(version), values, self.validity)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			pre: Pre::from_struct_array(
				values[0]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			post: Post::from_struct_array(
				values[1]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			validity: validity,
		}
	}
}

impl PortData {
	fn fields(version: Version, port: PortOccupancy) -> Fields {
		let mut fields = vec![Field::new(
			"leader",
			Data::data_type(version).clone(),
			false,
		)];
		if port.follower {
			fields.push(Field::new(
				"follower",
				Data::data_type(version).clone(),
				false,
			));
		}
		Fields::from(fields)
	}

	fn data_type(version: Version, port: PortOccupancy) -> DataType {
		DataType::Struct(Self::fields(version, port))
	}

	fn into_struct_array(self, version: Version, port: PortOccupancy) -> StructArray {
		let mut values = vec![Arc::new(self.leader.into_struct_array(version)) as Arc<dyn Array>];
		if let Some(follower) = self.follower {
			values.push(Arc::new(follower.into_struct_array(version)) as Arc<dyn Array>);
		}
		StructArray::new(Self::fields(version, port), values, None)
	}

	fn from_struct_array(array: StructArray, version: Version, port: Port) -> Self {
		let (fields, values, _) = array.into_parts();
		assert_eq!("leader", fields[0].name());
		fields.get(1).map(|f| assert_eq!("follower", f.name()));
		Self {
			port: port,
			leader: Data::from_struct_array(
				values[0]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			follower: values.get(1).map(|x| {
				Data::from_struct_array(
					x.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
		}
	}
}

impl Frame {
	fn port_fields(version: Version, ports: &[PortOccupancy]) -> Fields {
		Fields::from(
			ports
				.iter()
				.map(|p| {
					Field::new(
						format!("{}", p.port),
						PortData::data_type(version, *p).clone(),
						false,
					)
				})
				.collect::<Vec<_>>(),
		)
	}

	fn port_data_type(version: Version, ports: &[PortOccupancy]) -> DataType {
		DataType::Struct(Self::port_fields(version, ports))
	}

	fn item_field(version: Version) -> Field {
		Field::new("item", Item::data_type(version), false)
	}

	fn item_data_type(version: Version) -> DataType {
		DataType::List(Arc::new(Self::item_field(version)))
	}

	fn fields(version: Version, ports: &[PortOccupancy]) -> Fields {
		let mut fields = vec![
			Field::new("id", DataType::Int32, false),
			Field::new("ports", Self::port_data_type(version, ports), false),
		];
		if version.gte(2, 2) {
			fields.push(Field::new(
				"start",
				Start::data_type(version).clone(),
				false,
			));
			if version.gte(3, 0) {
				fields.push(Field::new("end", End::data_type(version).clone(), false));
				fields.push(Field::new(
					"item",
					Self::item_data_type(version).clone(),
					false,
				));
			}
		}
		Fields::from(fields)
	}

	pub fn into_struct_array(self, version: Version, ports: &[PortOccupancy]) -> StructArray {
		let values: Vec<_> = std::iter::zip(ports, self.ports)
			.map(|(occupancy, data)| {
				Arc::new(data.into_struct_array(version, *occupancy)) as Arc<dyn Array>
			})
			.collect();

		let mut arrays = vec![
			Arc::new(self.id) as Arc<dyn Array>,
			Arc::new(StructArray::new(
				Self::port_fields(version, ports),
				values,
				None,
			)) as Arc<dyn Array>,
		];

		if version.gte(2, 2) {
			arrays.push(Arc::new(self.start.unwrap().into_struct_array(version)) as Arc<dyn Array>);
			if version.gte(3, 0) {
				arrays
					.push(Arc::new(self.end.unwrap().into_struct_array(version)) as Arc<dyn Array>);
				let item_values = Arc::new(self.item.unwrap().into_struct_array(version));
				arrays.push(Arc::new(ListArray::new(
					Arc::new(Self::item_field(version)),
					self.item_offset.unwrap(),
					item_values,
					None,
				)) as Arc<dyn Array>);
			}
		}

		StructArray::new(Self::fields(version, ports), arrays, None)
	}

	fn port_data_from_struct_array(array: StructArray, version: Version) -> Vec<PortData> {
		let (fields, values, _) = array.into_parts();
		let mut ports = vec![];
		for i in 0..NUM_PORTS {
			if let Some(a) = values.get(i as usize) {
				ports.push(PortData::from_struct_array(
					a.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
					Port::parse(&fields[i as usize].name()).unwrap(),
				));
			}
		}
		ports
	}

	pub fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (fields, values, _) = array.into_parts();
		assert_eq!("id", fields[0].name());
		assert_eq!("ports", fields[1].name());
		if version.gte(2, 2) {
			assert_eq!("start", fields[2].name());
			if version.gte(3, 0) {
				assert_eq!("end", fields[3].name());
				assert_eq!("item", fields[4].name());
			}
		}

		let (item, item_offset) = values.get(4).map_or((None, None), |v| {
			let arrays = v.as_any().downcast_ref::<ListArray>().unwrap().clone();
			let item_offset = arrays.offsets().clone();
			let item = Item::from_struct_array(
				arrays
					.values()
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			);
			(Some(item), Some(item_offset))
		});

		Self {
			id: values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<Int32Type>>()
				.unwrap()
				.clone(),
			ports: Self::port_data_from_struct_array(
				values[1]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			start: values.get(2).map(|v| {
				Start::from_struct_array(
					v.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			end: values.get(3).map(|v| {
				End::from_struct_array(
					v.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			item_offset: item_offset,
			item: item,
		}
	}
}

use crate::frame::immutable::End;

impl End {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			if version.gte(3, 7) {
				fields.push(Field::new("latest_finalized_frame", DataType::Int32, false))
			}
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		if version.gte(3, 7) {
			values.push(Arc::new(self.latest_finalized_frame.unwrap()) as Arc<dyn Array>)
		};
		StructArray::new(Self::fields(version), values, self.validity)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			latest_finalized_frame: values.get(0).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<Int32Type>>()
					.unwrap()
					.clone()
			}),
			validity: validity,
		}
	}
}

use crate::frame::immutable::Item;

impl Item {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("type", DataType::UInt16, false));
			fields.push(Field::new("state", DataType::UInt8, false));
			fields.push(Field::new("direction", DataType::Float32, false));
			fields.push(Field::new("velocity", Velocity::data_type(version), false));
			fields.push(Field::new("position", Position::data_type(version), false));
			fields.push(Field::new("damage", DataType::UInt16, false));
			fields.push(Field::new("timer", DataType::Float32, false));
			fields.push(Field::new("id", DataType::UInt32, false));
			if version.gte(3, 2) {
				fields.push(Field::new("misc", ItemMisc::data_type(version), false));
				if version.gte(3, 6) {
					fields.push(Field::new("owner", DataType::Int8, false));
					if version.gte(3, 16) {
						fields.push(Field::new("instance_id", DataType::UInt16, false))
					}
				}
			}
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(self.r#type) as Arc<dyn Array>);
		values.push(Arc::new(self.state) as Arc<dyn Array>);
		values.push(Arc::new(self.direction) as Arc<dyn Array>);
		values.push(Arc::new(self.velocity.into_struct_array(version)) as Arc<dyn Array>);
		values.push(Arc::new(self.position.into_struct_array(version)) as Arc<dyn Array>);
		values.push(Arc::new(self.damage) as Arc<dyn Array>);
		values.push(Arc::new(self.timer) as Arc<dyn Array>);
		values.push(Arc::new(self.id) as Arc<dyn Array>);
		if version.gte(3, 2) {
			values.push(Arc::new(self.misc.unwrap().into_struct_array(version)) as Arc<dyn Array>);
			if version.gte(3, 6) {
				values.push(Arc::new(self.owner.unwrap()) as Arc<dyn Array>);
				if version.gte(3, 16) {
					values.push(Arc::new(self.instance_id.unwrap()) as Arc<dyn Array>)
				}
			}
		};
		StructArray::new(Self::fields(version), values, self.validity)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			r#type: values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt16Type>>()
				.unwrap()
				.clone(),
			state: values[1]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			direction: values[2]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			velocity: Velocity::from_struct_array(
				values[3]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			position: Position::from_struct_array(
				values[4]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			damage: values[5]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt16Type>>()
				.unwrap()
				.clone(),
			timer: values[6]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			id: values[7]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt32Type>>()
				.unwrap()
				.clone(),
			misc: values.get(8).map(|x| {
				ItemMisc::from_struct_array(
					x.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			owner: values.get(9).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<Int8Type>>()
					.unwrap()
					.clone()
			}),
			instance_id: values.get(10).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<UInt16Type>>()
					.unwrap()
					.clone()
			}),
			validity: validity,
		}
	}
}

use crate::frame::immutable::ItemMisc;

impl ItemMisc {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("0", DataType::UInt8, false));
			fields.push(Field::new("1", DataType::UInt8, false));
			fields.push(Field::new("2", DataType::UInt8, false));
			fields.push(Field::new("3", DataType::UInt8, false))
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(self.0) as Arc<dyn Array>);
		values.push(Arc::new(self.1) as Arc<dyn Array>);
		values.push(Arc::new(self.2) as Arc<dyn Array>);
		values.push(Arc::new(self.3) as Arc<dyn Array>);
		StructArray::new(Self::fields(version), values, None)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self(
			values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			values[1]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			values[2]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			values[3]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
		)
	}
}

use crate::frame::immutable::Position;

impl Position {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("x", DataType::Float32, false));
			fields.push(Field::new("y", DataType::Float32, false))
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(self.x) as Arc<dyn Array>);
		values.push(Arc::new(self.y) as Arc<dyn Array>);
		StructArray::new(Self::fields(version), values, self.validity)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			x: values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			y: values[1]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			validity: validity,
		}
	}
}

use crate::frame::immutable::Post;

impl Post {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("character", DataType::UInt8, false));
			fields.push(Field::new("state", DataType::UInt16, false));
			fields.push(Field::new("position", Position::data_type(version), false));
			fields.push(Field::new("direction", DataType::Float32, false));
			fields.push(Field::new("percent", DataType::Float32, false));
			fields.push(Field::new("shield", DataType::Float32, false));
			fields.push(Field::new("last_attack_landed", DataType::UInt8, false));
			fields.push(Field::new("combo_count", DataType::UInt8, false));
			fields.push(Field::new("last_hit_by", DataType::UInt8, false));
			fields.push(Field::new("stocks", DataType::UInt8, false));
			if version.gte(0, 2) {
				fields.push(Field::new("state_age", DataType::Float32, false));
				if version.gte(2, 0) {
					fields.push(Field::new(
						"state_flags",
						StateFlags::data_type(version),
						false,
					));
					fields.push(Field::new("misc_as", DataType::Float32, false));
					fields.push(Field::new("airborne", DataType::UInt8, false));
					fields.push(Field::new("ground", DataType::UInt16, false));
					fields.push(Field::new("jumps", DataType::UInt8, false));
					fields.push(Field::new("l_cancel", DataType::UInt8, false));
					if version.gte(2, 1) {
						fields.push(Field::new("hurtbox_state", DataType::UInt8, false));
						if version.gte(3, 5) {
							fields.push(Field::new(
								"velocities",
								Velocities::data_type(version),
								false,
							));
							if version.gte(3, 8) {
								fields.push(Field::new("hitlag", DataType::Float32, false));
								if version.gte(3, 11) {
									fields.push(Field::new(
										"animation_index",
										DataType::UInt32,
										false,
									));
									if version.gte(3, 16) {
										fields.push(Field::new(
											"last_hit_by_instance",
											DataType::UInt16,
											false,
										));
										fields.push(Field::new(
											"instance_id",
											DataType::UInt16,
											false,
										))
									}
								}
							}
						}
					}
				}
			}
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(self.character) as Arc<dyn Array>);
		values.push(Arc::new(self.state) as Arc<dyn Array>);
		values.push(Arc::new(self.position.into_struct_array(version)) as Arc<dyn Array>);
		values.push(Arc::new(self.direction) as Arc<dyn Array>);
		values.push(Arc::new(self.percent) as Arc<dyn Array>);
		values.push(Arc::new(self.shield) as Arc<dyn Array>);
		values.push(Arc::new(self.last_attack_landed) as Arc<dyn Array>);
		values.push(Arc::new(self.combo_count) as Arc<dyn Array>);
		values.push(Arc::new(self.last_hit_by) as Arc<dyn Array>);
		values.push(Arc::new(self.stocks) as Arc<dyn Array>);
		if version.gte(0, 2) {
			values.push(Arc::new(self.state_age.unwrap()) as Arc<dyn Array>);
			if version.gte(2, 0) {
				values.push(
					Arc::new(self.state_flags.unwrap().into_struct_array(version))
						as Arc<dyn Array>,
				);
				values.push(Arc::new(self.misc_as.unwrap()) as Arc<dyn Array>);
				values.push(Arc::new(self.airborne.unwrap()) as Arc<dyn Array>);
				values.push(Arc::new(self.ground.unwrap()) as Arc<dyn Array>);
				values.push(Arc::new(self.jumps.unwrap()) as Arc<dyn Array>);
				values.push(Arc::new(self.l_cancel.unwrap()) as Arc<dyn Array>);
				if version.gte(2, 1) {
					values.push(Arc::new(self.hurtbox_state.unwrap()) as Arc<dyn Array>);
					if version.gte(3, 5) {
						values.push(
							Arc::new(self.velocities.unwrap().into_struct_array(version))
								as Arc<dyn Array>,
						);
						if version.gte(3, 8) {
							values.push(Arc::new(self.hitlag.unwrap()) as Arc<dyn Array>);
							if version.gte(3, 11) {
								values
									.push(Arc::new(self.animation_index.unwrap()) as Arc<dyn Array>);
								if version.gte(3, 16) {
									values.push(Arc::new(self.last_hit_by_instance.unwrap())
										as Arc<dyn Array>);
									values
										.push(Arc::new(self.instance_id.unwrap()) as Arc<dyn Array>)
								}
							}
						}
					}
				}
			}
		};
		StructArray::new(Self::fields(version), values, self.validity)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			character: values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			state: values[1]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt16Type>>()
				.unwrap()
				.clone(),
			position: Position::from_struct_array(
				values[2]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			direction: values[3]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			percent: values[4]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			shield: values[5]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			last_attack_landed: values[6]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			combo_count: values[7]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			last_hit_by: values[8]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			stocks: values[9]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			state_age: values.get(10).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<Float32Type>>()
					.unwrap()
					.clone()
			}),
			state_flags: values.get(11).map(|x| {
				StateFlags::from_struct_array(
					x.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			misc_as: values.get(12).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<Float32Type>>()
					.unwrap()
					.clone()
			}),
			airborne: values.get(13).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<UInt8Type>>()
					.unwrap()
					.clone()
			}),
			ground: values.get(14).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<UInt16Type>>()
					.unwrap()
					.clone()
			}),
			jumps: values.get(15).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<UInt8Type>>()
					.unwrap()
					.clone()
			}),
			l_cancel: values.get(16).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<UInt8Type>>()
					.unwrap()
					.clone()
			}),
			hurtbox_state: values.get(17).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<UInt8Type>>()
					.unwrap()
					.clone()
			}),
			velocities: values.get(18).map(|x| {
				Velocities::from_struct_array(
					x.as_any().downcast_ref::<StructArray>().unwrap().clone(),
					version,
				)
			}),
			hitlag: values.get(19).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<Float32Type>>()
					.unwrap()
					.clone()
			}),
			animation_index: values.get(20).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<UInt32Type>>()
					.unwrap()
					.clone()
			}),
			last_hit_by_instance: values.get(21).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<UInt16Type>>()
					.unwrap()
					.clone()
			}),
			instance_id: values.get(22).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<UInt16Type>>()
					.unwrap()
					.clone()
			}),
			validity: validity,
		}
	}
}

use crate::frame::immutable::Pre;

impl Pre {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("random_seed", DataType::UInt32, false));
			fields.push(Field::new("state", DataType::UInt16, false));
			fields.push(Field::new("position", Position::data_type(version), false));
			fields.push(Field::new("direction", DataType::Float32, false));
			fields.push(Field::new("joystick", Position::data_type(version), false));
			fields.push(Field::new("cstick", Position::data_type(version), false));
			fields.push(Field::new("triggers", DataType::Float32, false));
			fields.push(Field::new("buttons", DataType::UInt32, false));
			fields.push(Field::new("buttons_physical", DataType::UInt16, false));
			fields.push(Field::new(
				"triggers_physical",
				TriggersPhysical::data_type(version),
				false,
			));
			if version.gte(1, 2) {
				fields.push(Field::new("raw_analog_x", DataType::Int8, false));
				if version.gte(1, 4) {
					fields.push(Field::new("percent", DataType::Float32, false));
					if version.gte(3, 15) {
						fields.push(Field::new("raw_analog_y", DataType::Int8, false))
					}
				}
			}
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(self.random_seed) as Arc<dyn Array>);
		values.push(Arc::new(self.state) as Arc<dyn Array>);
		values.push(Arc::new(self.position.into_struct_array(version)) as Arc<dyn Array>);
		values.push(Arc::new(self.direction) as Arc<dyn Array>);
		values.push(Arc::new(self.joystick.into_struct_array(version)) as Arc<dyn Array>);
		values.push(Arc::new(self.cstick.into_struct_array(version)) as Arc<dyn Array>);
		values.push(Arc::new(self.triggers) as Arc<dyn Array>);
		values.push(Arc::new(self.buttons) as Arc<dyn Array>);
		values.push(Arc::new(self.buttons_physical) as Arc<dyn Array>);
		values.push(Arc::new(self.triggers_physical.into_struct_array(version)) as Arc<dyn Array>);
		if version.gte(1, 2) {
			values.push(Arc::new(self.raw_analog_x.unwrap()) as Arc<dyn Array>);
			if version.gte(1, 4) {
				values.push(Arc::new(self.percent.unwrap()) as Arc<dyn Array>);
				if version.gte(3, 15) {
					values.push(Arc::new(self.raw_analog_y.unwrap()) as Arc<dyn Array>)
				}
			}
		};
		StructArray::new(Self::fields(version), values, self.validity)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			random_seed: values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt32Type>>()
				.unwrap()
				.clone(),
			state: values[1]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt16Type>>()
				.unwrap()
				.clone(),
			position: Position::from_struct_array(
				values[2]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			direction: values[3]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			joystick: Position::from_struct_array(
				values[4]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			cstick: Position::from_struct_array(
				values[5]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			triggers: values[6]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			buttons: values[7]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt32Type>>()
				.unwrap()
				.clone(),
			buttons_physical: values[8]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt16Type>>()
				.unwrap()
				.clone(),
			triggers_physical: TriggersPhysical::from_struct_array(
				values[9]
					.as_any()
					.downcast_ref::<StructArray>()
					.unwrap()
					.clone(),
				version,
			),
			raw_analog_x: values.get(10).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<Int8Type>>()
					.unwrap()
					.clone()
			}),
			percent: values.get(11).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<Float32Type>>()
					.unwrap()
					.clone()
			}),
			raw_analog_y: values.get(12).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<Int8Type>>()
					.unwrap()
					.clone()
			}),
			validity: validity,
		}
	}
}

use crate::frame::immutable::Start;

impl Start {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("random_seed", DataType::UInt32, false));
			if version.gte(3, 10) {
				fields.push(Field::new("scene_frame_counter", DataType::UInt32, false))
			}
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(self.random_seed) as Arc<dyn Array>);
		if version.gte(3, 10) {
			values.push(Arc::new(self.scene_frame_counter.unwrap()) as Arc<dyn Array>)
		};
		StructArray::new(Self::fields(version), values, self.validity)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			random_seed: values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt32Type>>()
				.unwrap()
				.clone(),
			scene_frame_counter: values.get(1).map(|x| {
				x.as_any()
					.downcast_ref::<PrimitiveArray<UInt32Type>>()
					.unwrap()
					.clone()
			}),
			validity: validity,
		}
	}
}

use crate::frame::immutable::StateFlags;

impl StateFlags {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("0", DataType::UInt8, false));
			fields.push(Field::new("1", DataType::UInt8, false));
			fields.push(Field::new("2", DataType::UInt8, false));
			fields.push(Field::new("3", DataType::UInt8, false));
			fields.push(Field::new("4", DataType::UInt8, false))
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(self.0) as Arc<dyn Array>);
		values.push(Arc::new(self.1) as Arc<dyn Array>);
		values.push(Arc::new(self.2) as Arc<dyn Array>);
		values.push(Arc::new(self.3) as Arc<dyn Array>);
		values.push(Arc::new(self.4) as Arc<dyn Array>);
		StructArray::new(Self::fields(version), values, None)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self(
			values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			values[1]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			values[2]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			values[3]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
			values[4]
				.as_any()
				.downcast_ref::<PrimitiveArray<UInt8Type>>()
				.unwrap()
				.clone(),
		)
	}
}

use crate::frame::immutable::TriggersPhysical;

impl TriggersPhysical {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("l", DataType::Float32, false));
			fields.push(Field::new("r", DataType::Float32, false))
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(self.l) as Arc<dyn Array>);
		values.push(Arc::new(self.r) as Arc<dyn Array>);
		StructArray::new(Self::fields(version), values, self.validity)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			l: values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			r: values[1]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			validity: validity,
		}
	}
}

use crate::frame::immutable::Velocities;

impl Velocities {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("self_x_air", DataType::Float32, false));
			fields.push(Field::new("self_y", DataType::Float32, false));
			fields.push(Field::new("knockback_x", DataType::Float32, false));
			fields.push(Field::new("knockback_y", DataType::Float32, false));
			fields.push(Field::new("self_x_ground", DataType::Float32, false))
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(self.self_x_air) as Arc<dyn Array>);
		values.push(Arc::new(self.self_y) as Arc<dyn Array>);
		values.push(Arc::new(self.knockback_x) as Arc<dyn Array>);
		values.push(Arc::new(self.knockback_y) as Arc<dyn Array>);
		values.push(Arc::new(self.self_x_ground) as Arc<dyn Array>);
		StructArray::new(Self::fields(version), values, self.validity)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			self_x_air: values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			self_y: values[1]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			knockback_x: values[2]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			knockback_y: values[3]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			self_x_ground: values[4]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			validity: validity,
		}
	}
}

use crate::frame::immutable::Velocity;

impl Velocity {
	fn fields(version: Version) -> Fields {
		let mut fields = vec![];
		{
			fields.push(Field::new("x", DataType::Float32, false));
			fields.push(Field::new("y", DataType::Float32, false))
		};
		Fields::from(fields)
	}

	fn data_type(version: Version) -> DataType {
		DataType::Struct(Self::fields(version))
	}

	fn into_struct_array(self, version: Version) -> StructArray {
		let mut values = vec![];
		values.push(Arc::new(self.x) as Arc<dyn Array>);
		values.push(Arc::new(self.y) as Arc<dyn Array>);
		StructArray::new(Self::fields(version), values, self.validity)
	}

	fn from_struct_array(array: StructArray, version: Version) -> Self {
		let (_, values, validity) = array.into_parts();
		Self {
			x: values[0]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			y: values[1]
				.as_any()
				.downcast_ref::<PrimitiveArray<Float32Type>>()
				.unwrap()
				.clone(),
			validity: validity,
		}
	}
}
