pseudo_enum!(Internal: u8 {
	00 => MARIO,
	01 => FOX,
	02 => CAPTAIN_FALCON,
	03 => DONKEY_KONG,
	04 => KIRBY,
	05 => BOWSER,
	06 => LINK,
	07 => SHEIK,
	08 => NESS,
	09 => PEACH,
	10 => POPO,
	11 => NANA,
	12 => PIKACHU,
	13 => SAMUS,
	14 => YOSHI,
	15 => JIGGLYPUFF,
	16 => MEWTWO,
	17 => LUIGI,
	18 => MARTH,
	19 => ZELDA,
	20 => YOUNG_LINK,
	21 => DR_MARIO,
	22 => FALCO,
	23 => PICHU,
	24 => GAME_AND_WATCH,
	25 => GANONDORF,
	26 => ROY,
	27 => MASTER_HAND,
	28 => CRAZY_HAND,
	29 => WIRE_FRAME_MALE,
	30 => WIRE_FRAME_FEMALE,
	31 => GIGA_BOWSER,
	32 => SANDBAG,
});

pseudo_enum!(External: u8 {
	00 => CAPTAIN_FALCON,
	01 => DONKEY_KONG,
	02 => FOX,
	03 => GAME_AND_WATCH,
	04 => KIRBY,
	05 => BOWSER,
	06 => LINK,
	07 => LUIGI,
	08 => MARIO,
	09 => MARTH,
	10 => MEWTWO,
	11 => NESS,
	12 => PEACH,
	13 => PIKACHU,
	14 => ICE_CLIMBERS,
	15 => JIGGLYPUFF,
	16 => SAMUS,
	17 => YOSHI,
	18 => ZELDA,
	19 => SHEIK,
	20 => FALCO,
	21 => YOUNG_LINK,
	22 => DR_MARIO,
	23 => ROY,
	24 => PICHU,
	25 => GANONDORF,
	26 => MASTER_HAND,
	27 => WIRE_FRAME_MALE,
	28 => WIRE_FRAME_FEMALE,
	29 => GIGA_BOWSER,
	30 => CRAZY_HAND,
	31 => SANDBAG,
	32 => POPO,
});

regex_match!(external : External {
	CAPTAIN_FALCON: r"(?i-u)^(capt(ain|\.)?[ _]?)?falcon$",
	DONKEY_KONG: r"(?i-u)^dk|(donkey[ _]?kong$",
	FOX: r"(?i-u)^fox$",
	GAME_AND_WATCH: r"(?i-u)^(g|game)[ _]?(and|&|n)[ _]?(w|watch)$",
	KIRBY: r"(?i-u)^kirby$",
	BOWSER: r"(?i-u)^bowser$",
	LINK: r"(?i-u)^link$",
	LUIGI: r"(?i-u)^luigi$",
	MARIO: r"(?i-u)^mario$",
	MARTH: r"(?i-u)^marth$",
	MEWTWO: r"(?i-u)^mewtwo|mew2|m2$",
	NESS: r"(?i-u)^ness$",
	PEACH: r"(?i-u)^peach$",
	PIKACHU: r"(?i-u)^pika(chu)?$",
	ICE_CLIMBERS: r"(?i-u)^ic(|s|ies|e[ _]?climbers)$",
	JIGGLYPUFF: r"(?i-u)^(jiggly)?puff|jiggs$",
	SAMUS: r"(?i-u)^samus$",
	YOSHI: r"(?i-u)^yoshi$",
	ZELDA: r"(?i-u)^zelda$",
	SHEIK: r"(?i-u)^sheik$",
	FALCO: r"(?i-u)^falco$",
	YOUNG_LINK: r"(?i-u)^yl|yink|(y\.?|young)[ _]?link$",
	DR_MARIO: r"(?i-u)^doc|dr\.?[ _]?mario$",
	ROY: r"(?i-u)^roy$",
	PICHU: r"(?i-u)^pichu$",
	GANONDORF: r"(?i-u)^ganon(dorf)?$",
	MASTER_HAND: r"(?i-u)^master[ _]?hand$",
	WIRE_FRAME_MALE: r"(?i-u)^male[ _]?wire[ _]?frame|wire[ _]?frame[ _]?male$",
	WIRE_FRAME_FEMALE: r"(?i-u)^female[ _]?wire[ _]?frame|wire[ _]?frame[ _]?female$",
	GIGA_BOWSER: r"(?i-u)^giga[ _]?bowser$",
	CRAZY_HAND: r"(?i-u)^crazy[ _]?hand$",
	SANDBAG: r"(?i-u)^sandbag$",
	POPO: r"(?i-u)^popo$",
});
