pseudo_enum!(Stage: u16 {
	02 => FOUNTAIN_OF_DREAMS,
	03 => POKEMON_STADIUM,
	04 => PRINCESS_PEACHS_CASTLE,
	05 => KONGO_JUNGLE,
	06 => BRINSTAR,
	07 => CORNERIA,
	08 => YOSHIS_STORY,
	09 => ONETT,
	10 => MUTE_CITY,
	11 => RAINBOW_CRUISE,
	12 => JUNGLE_JAPES,
	13 => GREAT_BAY,
	14 => HYRULE_TEMPLE,
	15 => BRINSTAR_DEPTHS,
	16 => YOSHIS_ISLAND,
	17 => GREEN_GREENS,
	18 => FOURSIDE,
	19 => MUSHROOM_KINGDOM_I,
	20 => MUSHROOM_KINGDOM_II,
	22 => VENOM,
	23 => POKE_FLOATS,
	24 => BIG_BLUE,
	25 => ICICLE_MOUNTAIN,
	26 => ICETOP,
	27 => FLAT_ZONE,
	28 => DREAM_LAND_N64,
	29 => YOSHIS_ISLAND_N64,
	30 => KONGO_JUNGLE_N64,
	31 => BATTLEFIELD,
	32 => FINAL_DESTINATION,
});

regex_match!(stage : Stage {
	FOUNTAIN_OF_DREAMS: r"(?i-u)^fod|fountain([ _]?of[ _]?dreams)?$",
	POKEMON_STADIUM: r"(?i-u)^ps|pokemon([ _]?stadium([ _]?[1I])?)?$",
	YOSHIS_STORY: r"(?i-u)^ys|yoshi'?s[ _]?story$",
	DREAM_LAND_N64: r"(?i-u)^(dl|dream[ _]?land)[ _]?(N?64)?$",
	BATTLEFIELD: r"(?i-u)^bf|battle[ _]?field$",
	FINAL_DESTINATION: r"(?i-u)^fd|final[ _]?destination$",
	PRINCESS_PEACHS_CASTLE: r"(?i-u)^ppc|princess[ _]?peach'?s[ _]?castle$",
	KONGO_JUNGLE: r"(?i-u)^kj|kongo[ _]?jungle$",
	BRINSTAR: r"(?i-u)^brinstar$",
	CORNERIA: r"(?i-u)^corneria$",
	ONETT: r"(?i-u)^onett$",
	MUTE_CITY: r"(?i-u)^mc|mute[ _]?city$",
	RAINBOW_CRUISE: r"(?i-u)^rc|rainbow[ _]?cruise$",
	JUNGLE_JAPES: r"(?i-u)^jj|jungle[ _]?japes$",
	GREAT_BAY: r"(?i-u)^gb|great[ _]?bay$",
	HYRULE_TEMPLE: r"(?i-u)^ht|hyrule[ _]?temple$",
	BRINSTAR_DEPTHS: r"(?i-u)^bd|brinstar[ _]?depths$",
	YOSHIS_ISLAND: r"(?i-u)^yi|yoshi'?s[ _]?island$",
	GREEN_GREENS: r"(?i-u)^gg|green[ _]?greens$",
	FOURSIDE: r"(?i-u)^fourside$",
	MUSHROOM_KINGDOM_I: r"(?i-u)^(mk|mushroom[ _]?kingdom)[1i]?$",
	MUSHROOM_KINGDOM_II: r"(?i-u)^(mk|mushroom[ _]?kingdom)(2|ii)$",
	VENOM: r"(?i-u)^venom$",
	POKE_FLOATS: r"(?i-u)^pf|poke[ _]?floats$",
	BIG_BLUE: r"(?i-u)^bb|big[ _]?blue$",
	ICICLE_MOUNTAIN: r"(?i-u)^im|icicle[ _]?mountain$",
	FLAT_ZONE: r"(?i-u)^fz|flat[ _]?zone$",
	YOSHIS_ISLAND_N64: r"(?i-u)^(yi|yoshi'?s[ _]?island)[ _]?(N?64)$",
	KONGO_JUNGLE_N64: r"(?i-u)^(kj|kongo[ _]?jungle)[ _]?(N?64)$",
});
