[package]
authors = ["melkor <hohav@fastmail.com>"]
description = "Support crate for peppi"
edition = "2021"
license = "MIT"
name = "peppi-arrow"
repository = "https://github.com/hohav/peppi"
version = "0.2.3"

[dependencies]
arrow = "20.0.0"
