// This file is auto-generated by `gen/scripts/frames`. Do not edit.

//! Mutable (in-progress) frame data.
//!
//! You’ll only encounter mutable frame data if you’re parsing live games.

#![allow(unused_variables)]
#![allow(dead_code)]

use arrow::array::{NullBufferBuilder, OffsetBufferBuilder};

use byteorder::ReadBytesExt;
use std::io::Result;
use std::mem;

use crate::{
	frame::{PortOccupancy, immutable, transpose},
	game::Port,
	io::slippi::Version,
};

type BE = byteorder::BigEndian;

fn start_end(buf: &Option<OffsetBufferBuilder<i32>>, i: usize) -> (usize, usize) {
	let b = buf.as_ref().unwrap();
	(b[i].try_into().unwrap(), b[i + 1].try_into().unwrap())
}

/// Frame data for a single character (ICs are two characters).
pub struct Data {
	pub pre: Pre,
	pub post: Post,
	pub validity: NullBufferBuilder,
}

impl Data {
	pub fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			pre: Pre::with_capacity(capacity, version),
			post: Post::with_capacity(capacity, version),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.pre.len()
	}

	pub fn append_null(&mut self, version: Version) {
		self.validity.append_null();
		self.pre.append_default(version);
		self.post.append_default(version);
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.pre.append_default(version);
		self.post.append_default(version);
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> Option<transpose::Data> {
		self.validity.is_valid(i).then(|| transpose::Data {
			pre: self.pre.transpose_one(i, version),
			post: self.post.transpose_one(i, version),
		})
	}

	pub fn finish(&mut self) -> immutable::Data {
		immutable::Data {
			pre: self.pre.finish(),
			post: self.post.finish(),
			validity: self.validity.finish(),
		}
	}
}

/// Frame data for a single port.
pub struct PortData {
	pub port: Port,
	pub leader: Data,
	/// The "backup" ICs character
	pub follower: Option<Data>,
	pub validity: NullBufferBuilder,
}

impl PortData {
	pub fn with_capacity(capacity: usize, version: Version, port: PortOccupancy) -> Self {
		Self {
			port: port.port,
			leader: Data::with_capacity(capacity, version),
			follower: match port.follower {
				true => Some(Data::with_capacity(capacity, version)),
				_ => None,
			},
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.leader.len()
	}

	pub fn append_null(&mut self, version: Version) {
		self.validity.append_null();
		self.leader.append_default(version);
		self.follower.as_mut().map(|f| f.append_default(version));
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> Option<transpose::PortData> {
		self.validity.is_valid(i).then(|| transpose::PortData {
			port: self.port,
			leader: self.leader.transpose_one(i, version).unwrap(),
			follower: self
				.follower
				.as_ref()
				.and_then(|f| f.transpose_one(i, version)),
		})
	}

	pub fn finish(&mut self) -> immutable::PortData {
		let Self {
			port,
			leader,
			follower,
			validity,
		} = self;
		immutable::PortData {
			port: *port,
			leader: leader.finish(),
			follower: follower.as_mut().map(|f| f.finish()),
			validity: validity.finish(),
		}
	}
}

/// All frame data for a single game, in struct-of-arrays format.
pub struct Frame {
	/// Frame IDs start at `-123` and increment each frame. May repeat in case of rollbacks
	pub id: Vec<i32>,
	/// Port-specific data
	pub ports: Vec<PortData>,
	/// Start-of-frame data
	pub start: Option<Start>,
	/// End-of-frame data
	pub end: Option<End>,

	/// Item data
	pub item: Option<Item>,
	/// Logically, each frame has its own array of items. But we represent all item data in a flat array, with this field indicating the start of each sub-array
	pub item_offset: Option<OffsetBufferBuilder<i32>>,

	pub fod_platform: Option<FodPlatform>,
	pub fod_platform_offset: Option<OffsetBufferBuilder<i32>>,

	pub dreamland_whispy: Option<DreamlandWhispy>,
	pub dreamland_whispy_offset: Option<OffsetBufferBuilder<i32>>,

	pub stadium_transformation: Option<StadiumTransformation>,
	pub stadium_transformation_offset: Option<OffsetBufferBuilder<i32>>,
}

impl Frame {
	pub fn with_capacity(capacity: usize, version: Version, ports: &[PortOccupancy]) -> Self {
		Self {
			id: Vec::with_capacity(capacity),
			ports: ports
				.iter()
				.map(|p| PortData::with_capacity(capacity, version, *p))
				.collect(),
			start: version
				.gte(2, 2)
				.then(|| Start::with_capacity(capacity, version)),
			end: version
				.gte(3, 0)
				.then(|| End::with_capacity(capacity, version)),
			item: version.gte(3, 0).then(|| Item::with_capacity(0, version)),
			item_offset: version
				.gte(3, 0)
				.then(|| OffsetBufferBuilder::<i32>::new(capacity)),
			fod_platform: version
				.gte(3, 18)
				.then(|| FodPlatform::with_capacity(0, version)),
			fod_platform_offset: version
				.gte(3, 18)
				.then(|| OffsetBufferBuilder::<i32>::new(capacity)),
			dreamland_whispy: version
				.gte(3, 18)
				.then(|| DreamlandWhispy::with_capacity(0, version)),
			dreamland_whispy_offset: version
				.gte(3, 18)
				.then(|| OffsetBufferBuilder::<i32>::new(capacity)),
			stadium_transformation: version
				.gte(3, 18)
				.then(|| StadiumTransformation::with_capacity(0, version)),
			stadium_transformation_offset: version
				.gte(3, 18)
				.then(|| OffsetBufferBuilder::<i32>::new(capacity)),
		}
	}

	pub fn len(&self) -> usize {
		self.id.len()
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Frame {
		transpose::Frame {
			id: self.id[i],
			ports: self
				.ports
				.iter()
				.map(|p| p.transpose_one(i, version))
				.collect(),
			start: version
				.gte(2, 2)
				.then(|| self.start.as_ref().unwrap().transpose_one(i, version)),
			end: version
				.gte(3, 0)
				.then(|| self.end.as_ref().unwrap().transpose_one(i, version)),
			items: version.gte(3, 0).then(|| {
				let (start, end) = start_end(&self.item_offset, i);
				(start..end)
					.map(|i| self.item.as_ref().unwrap().transpose_one(i, version))
					.collect()
			}),
			fod_platforms: version.gte(3, 18).then(|| {
				let (start, end) = start_end(&self.fod_platform_offset, i);
				(start..end)
					.map(|i| {
						self.fod_platform
							.as_ref()
							.unwrap()
							.transpose_one(i, version)
					})
					.collect()
			}),
			dreamland_whispys: version.gte(3, 18).then(|| {
				let (start, end) = start_end(&self.dreamland_whispy_offset, i);
				(start..end)
					.map(|i| {
						self.dreamland_whispy
							.as_ref()
							.unwrap()
							.transpose_one(i, version)
					})
					.collect()
			}),
			stadium_transformations: version.gte(3, 18).then(|| {
				let (start, end) = start_end(&self.stadium_transformation_offset, i);
				(start..end)
					.map(|i| {
						self.stadium_transformation
							.as_ref()
							.unwrap()
							.transpose_one(i, version)
					})
					.collect()
			}),
		}
	}

	pub fn finish(&mut self) -> immutable::Frame {
		immutable::Frame {
			id: mem::take(&mut self.id),
			ports: self.ports.iter_mut().map(|p| p.finish()).collect(),
			start: self.start.as_mut().map(|x| x.finish()),
			end: self.end.as_mut().map(|x| x.finish()),
			item: self.item.as_mut().map(|x| x.finish()),
			item_offset: self.item_offset.take().map(|x| x.finish()),
			fod_platform: self.fod_platform.as_mut().map(|x| x.finish()),
			fod_platform_offset: self.fod_platform_offset.take().map(|x| x.finish()),
			dreamland_whispy: self.dreamland_whispy.as_mut().map(|x| x.finish()),
			dreamland_whispy_offset: self.dreamland_whispy_offset.take().map(|x| x.finish()),
			stadium_transformation: self.stadium_transformation.as_mut().map(|x| x.finish()),
			stadium_transformation_offset: self
				.stadium_transformation_offset
				.take()
				.map(|x| x.finish()),
		}
	}
}

/// This event only occurs on Dreamland 64, and is sent whenever Whispy changes blow directions.

pub struct DreamlandWhispy {
	/// Which direction Whispy is blowing (0 = None, 1 = Left, 2 = Right)
	pub direction: Vec<u8>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl DreamlandWhispy {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			direction: Vec::with_capacity(capacity),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.direction.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.direction.push(0u8)
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u8().map(|x| self.direction.push(x))?;
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::DreamlandWhispy {
		immutable::DreamlandWhispy {
			direction: mem::take(&mut self.direction),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::DreamlandWhispy {
		transpose::DreamlandWhispy {
			direction: self.direction[i],
		}
	}
}

/// Information about the end of the game.

pub struct End {
	/// *Added: v3.7* Index of the latest frame which is guaranteed not to happen again (rollback)
	pub latest_finalized_frame: Option<Vec<i32>>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl End {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			latest_finalized_frame: version.gte(3, 7).then(|| Vec::with_capacity(capacity)),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.validity.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		if version.gte(3, 7) {
			self.latest_finalized_frame.as_mut().unwrap().push(0i32)
		}
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		if version.gte(3, 7) {
			r.read_i32::<BE>()
				.map(|x| self.latest_finalized_frame.as_mut().unwrap().push(x))?
		};
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::End {
		immutable::End {
			latest_finalized_frame: mem::take(&mut self.latest_finalized_frame),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::End {
		transpose::End {
			latest_finalized_frame: self.latest_finalized_frame.as_ref().map(|x| x[i]),
		}
	}
}

/// This event only occurs on Fountain of Dreams, and is sent for each change in platform height. If both platforms are moving, there will be two events per frame.

pub struct FodPlatform {
	/// Which platform has moved. (0 = Right, 1 = Left)
	pub platform: Vec<u8>,
	/// The platform's new height
	pub height: Vec<f32>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl FodPlatform {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			platform: Vec::with_capacity(capacity),
			height: Vec::with_capacity(capacity),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.platform.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.platform.push(0u8);
		self.height.push(0f32)
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u8().map(|x| self.platform.push(x))?;
		r.read_f32::<BE>().map(|x| self.height.push(x))?;
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::FodPlatform {
		immutable::FodPlatform {
			platform: mem::take(&mut self.platform),
			height: mem::take(&mut self.height),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::FodPlatform {
		transpose::FodPlatform {
			platform: self.platform[i],
			height: self.height[i],
		}
	}
}

/// An active item (includes projectiles).

pub struct Item {
	/// Item type
	pub r#type: Vec<u16>,
	/// Item’s action state
	pub state: Vec<u8>,
	/// Direction item is facing
	pub direction: Vec<f32>,
	/// Item’s velocity
	pub velocity: Velocity,
	/// Item’s position
	pub position: Position,
	/// Amount of damage item has taken
	pub damage: Vec<u16>,
	/// Frames remaining until item expires
	pub timer: Vec<f32>,
	/// Unique, serial ID per item spawned
	pub id: Vec<u32>,
	/// *Added: v3.2* Miscellaneous item state
	pub misc: Option<ItemMisc>,
	/// *Added: v3.6* Port that owns the item (-1 when unowned)
	pub owner: Option<Vec<i8>>,
	/// *Added: v3.16* Inherited instance ID of the owner (0 when unowned)
	pub instance_id: Option<Vec<u16>>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl Item {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			r#type: Vec::with_capacity(capacity),
			state: Vec::with_capacity(capacity),
			direction: Vec::with_capacity(capacity),
			velocity: Velocity::with_capacity(capacity, version),
			position: Position::with_capacity(capacity, version),
			damage: Vec::with_capacity(capacity),
			timer: Vec::with_capacity(capacity),
			id: Vec::with_capacity(capacity),
			misc: version
				.gte(3, 2)
				.then(|| ItemMisc::with_capacity(capacity, version)),
			owner: version.gte(3, 6).then(|| Vec::with_capacity(capacity)),
			instance_id: version.gte(3, 16).then(|| Vec::with_capacity(capacity)),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.r#type.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.r#type.push(0u16);
		self.state.push(0u8);
		self.direction.push(0f32);
		self.velocity.append_default(version);
		self.position.append_default(version);
		self.damage.push(0u16);
		self.timer.push(0f32);
		self.id.push(0u32);
		if version.gte(3, 2) {
			self.misc.as_mut().unwrap().append_default(version);
			if version.gte(3, 6) {
				self.owner.as_mut().unwrap().push(0i8);
				if version.gte(3, 16) {
					self.instance_id.as_mut().unwrap().push(0u16)
				}
			}
		}
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u16::<BE>().map(|x| self.r#type.push(x))?;
		r.read_u8().map(|x| self.state.push(x))?;
		r.read_f32::<BE>().map(|x| self.direction.push(x))?;
		self.velocity.read_append(r, version)?;
		self.position.read_append(r, version)?;
		r.read_u16::<BE>().map(|x| self.damage.push(x))?;
		r.read_f32::<BE>().map(|x| self.timer.push(x))?;
		r.read_u32::<BE>().map(|x| self.id.push(x))?;
		if version.gte(3, 2) {
			self.misc.as_mut().unwrap().read_append(r, version)?;
			if version.gte(3, 6) {
				r.read_i8().map(|x| self.owner.as_mut().unwrap().push(x))?;
				if version.gte(3, 16) {
					r.read_u16::<BE>()
						.map(|x| self.instance_id.as_mut().unwrap().push(x))?
				}
			}
		};
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::Item {
		immutable::Item {
			r#type: mem::take(&mut self.r#type),
			state: mem::take(&mut self.state),
			direction: mem::take(&mut self.direction),
			velocity: self.velocity.finish(),
			position: self.position.finish(),
			damage: mem::take(&mut self.damage),
			timer: mem::take(&mut self.timer),
			id: mem::take(&mut self.id),
			misc: self.misc.as_mut().map(|x| x.finish()),
			owner: mem::take(&mut self.owner),
			instance_id: mem::take(&mut self.instance_id),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Item {
		transpose::Item {
			r#type: self.r#type[i],
			state: self.state[i],
			direction: self.direction[i],
			velocity: self.velocity.transpose_one(i, version),
			position: self.position.transpose_one(i, version),
			damage: self.damage[i],
			timer: self.timer[i],
			id: self.id[i],
			misc: self.misc.as_ref().map(|x| x.transpose_one(i, version)),
			owner: self.owner.as_ref().map(|x| x[i]),
			instance_id: self.instance_id.as_ref().map(|x| x[i]),
		}
	}
}

/// Miscellaneous item state.

pub struct ItemMisc(pub Vec<u8>, pub Vec<u8>, pub Vec<u8>, pub Vec<u8>);

impl ItemMisc {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self(
			Vec::with_capacity(capacity),
			Vec::with_capacity(capacity),
			Vec::with_capacity(capacity),
			Vec::with_capacity(capacity),
		)
	}

	pub fn len(&self) -> usize {
		self.0.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.0.push(0u8);
		self.1.push(0u8);
		self.2.push(0u8);
		self.3.push(0u8)
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u8().map(|x| self.0.push(x))?;
		r.read_u8().map(|x| self.1.push(x))?;
		r.read_u8().map(|x| self.2.push(x))?;
		r.read_u8().map(|x| self.3.push(x))?;
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::ItemMisc {
		immutable::ItemMisc(
			mem::take(&mut self.0),
			mem::take(&mut self.1),
			mem::take(&mut self.2),
			mem::take(&mut self.3),
		)
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::ItemMisc {
		transpose::ItemMisc(self.0[i], self.1[i], self.2[i], self.3[i])
	}
}

/// 2D position.

pub struct Position {
	pub x: Vec<f32>,
	pub y: Vec<f32>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl Position {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			x: Vec::with_capacity(capacity),
			y: Vec::with_capacity(capacity),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.x.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.x.push(0f32);
		self.y.push(0f32)
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_f32::<BE>().map(|x| self.x.push(x))?;
		r.read_f32::<BE>().map(|x| self.y.push(x))?;
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::Position {
		immutable::Position {
			x: mem::take(&mut self.x),
			y: mem::take(&mut self.y),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Position {
		transpose::Position {
			x: self.x[i],
			y: self.y[i],
		}
	}
}

/// Post-frame update data, for making decisions about game states (such as computing stats).
///
/// Information is collected at the end of collision detection, which is the last consideration of the game engine.

pub struct Post {
	/// In-game character (can only change for Zelda/Sheik)
	pub character: Vec<u8>,
	/// Character’s action state
	pub state: Vec<u16>,
	/// Character’s position
	pub position: Position,
	/// Direction the character is facing
	pub direction: Vec<f32>,
	/// Damage taken (percent)
	pub percent: Vec<f32>,
	/// Size/health of shield
	pub shield: Vec<f32>,
	/// Last attack ID that this character landed
	pub last_attack_landed: Vec<u8>,
	/// Combo count (as defined by the game)
	pub combo_count: Vec<u8>,
	/// Port that last hit this player. Bugged in Melee: will be set to `6` in certain situations
	pub last_hit_by: Vec<u8>,
	/// Number of stocks remaining
	pub stocks: Vec<u8>,
	/// *Added: v0.2* Number of frames action state has been active. Can have a fractional component
	pub state_age: Option<Vec<f32>>,
	/// *Added: v2.0* State flags
	pub state_flags: Option<StateFlags>,
	/// *Added: v2.0* Used for different things. While in hitstun, contains hitstun frames remaining
	pub misc_as: Option<Vec<f32>>,
	/// *Added: v2.0* Is the character airborne?
	pub airborne: Option<Vec<u8>>,
	/// *Added: v2.0* Ground ID the character last touched
	pub ground: Option<Vec<u16>>,
	/// *Added: v2.0* Number of jumps remaining
	pub jumps: Option<Vec<u8>>,
	/// *Added: v2.0* L-cancel status (0 = none, 1 = successful, 2 = unsuccessful)
	pub l_cancel: Option<Vec<u8>>,
	/// *Added: v2.1* Hurtbox state (0 = vulnerable, 1 = invulnerable, 2 = intangible)
	pub hurtbox_state: Option<Vec<u8>>,
	/// *Added: v3.5* Self-induced and knockback velocities
	pub velocities: Option<Velocities>,
	/// *Added: v3.8* Hitlag frames remaining
	pub hitlag: Option<Vec<f32>>,
	/// *Added: v3.11* Animation the character is in
	pub animation_index: Option<Vec<u32>>,
	/// *Added: v3.16* Instance ID of the player/item that last hit this player
	pub last_hit_by_instance: Option<Vec<u16>>,
	/// *Added: v3.16* Unique, serial ID for each new action state across all characters. Resets to 0 on death
	pub instance_id: Option<Vec<u16>>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl Post {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			character: Vec::with_capacity(capacity),
			state: Vec::with_capacity(capacity),
			position: Position::with_capacity(capacity, version),
			direction: Vec::with_capacity(capacity),
			percent: Vec::with_capacity(capacity),
			shield: Vec::with_capacity(capacity),
			last_attack_landed: Vec::with_capacity(capacity),
			combo_count: Vec::with_capacity(capacity),
			last_hit_by: Vec::with_capacity(capacity),
			stocks: Vec::with_capacity(capacity),
			state_age: version.gte(0, 2).then(|| Vec::with_capacity(capacity)),
			state_flags: version
				.gte(2, 0)
				.then(|| StateFlags::with_capacity(capacity, version)),
			misc_as: version.gte(2, 0).then(|| Vec::with_capacity(capacity)),
			airborne: version.gte(2, 0).then(|| Vec::with_capacity(capacity)),
			ground: version.gte(2, 0).then(|| Vec::with_capacity(capacity)),
			jumps: version.gte(2, 0).then(|| Vec::with_capacity(capacity)),
			l_cancel: version.gte(2, 0).then(|| Vec::with_capacity(capacity)),
			hurtbox_state: version.gte(2, 1).then(|| Vec::with_capacity(capacity)),
			velocities: version
				.gte(3, 5)
				.then(|| Velocities::with_capacity(capacity, version)),
			hitlag: version.gte(3, 8).then(|| Vec::with_capacity(capacity)),
			animation_index: version.gte(3, 11).then(|| Vec::with_capacity(capacity)),
			last_hit_by_instance: version.gte(3, 16).then(|| Vec::with_capacity(capacity)),
			instance_id: version.gte(3, 16).then(|| Vec::with_capacity(capacity)),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.character.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.character.push(0u8);
		self.state.push(0u16);
		self.position.append_default(version);
		self.direction.push(0f32);
		self.percent.push(0f32);
		self.shield.push(0f32);
		self.last_attack_landed.push(0u8);
		self.combo_count.push(0u8);
		self.last_hit_by.push(0u8);
		self.stocks.push(0u8);
		if version.gte(0, 2) {
			self.state_age.as_mut().unwrap().push(0f32);
			if version.gte(2, 0) {
				self.state_flags.as_mut().unwrap().append_default(version);
				self.misc_as.as_mut().unwrap().push(0f32);
				self.airborne.as_mut().unwrap().push(0u8);
				self.ground.as_mut().unwrap().push(0u16);
				self.jumps.as_mut().unwrap().push(0u8);
				self.l_cancel.as_mut().unwrap().push(0u8);
				if version.gte(2, 1) {
					self.hurtbox_state.as_mut().unwrap().push(0u8);
					if version.gte(3, 5) {
						self.velocities.as_mut().unwrap().append_default(version);
						if version.gte(3, 8) {
							self.hitlag.as_mut().unwrap().push(0f32);
							if version.gte(3, 11) {
								self.animation_index.as_mut().unwrap().push(0u32);
								if version.gte(3, 16) {
									self.last_hit_by_instance.as_mut().unwrap().push(0u16);
									self.instance_id.as_mut().unwrap().push(0u16)
								}
							}
						}
					}
				}
			}
		}
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u8().map(|x| self.character.push(x))?;
		r.read_u16::<BE>().map(|x| self.state.push(x))?;
		self.position.read_append(r, version)?;
		r.read_f32::<BE>().map(|x| self.direction.push(x))?;
		r.read_f32::<BE>().map(|x| self.percent.push(x))?;
		r.read_f32::<BE>().map(|x| self.shield.push(x))?;
		r.read_u8().map(|x| self.last_attack_landed.push(x))?;
		r.read_u8().map(|x| self.combo_count.push(x))?;
		r.read_u8().map(|x| self.last_hit_by.push(x))?;
		r.read_u8().map(|x| self.stocks.push(x))?;
		if version.gte(0, 2) {
			r.read_f32::<BE>()
				.map(|x| self.state_age.as_mut().unwrap().push(x))?;
			if version.gte(2, 0) {
				self.state_flags.as_mut().unwrap().read_append(r, version)?;
				r.read_f32::<BE>()
					.map(|x| self.misc_as.as_mut().unwrap().push(x))?;
				r.read_u8()
					.map(|x| self.airborne.as_mut().unwrap().push(x))?;
				r.read_u16::<BE>()
					.map(|x| self.ground.as_mut().unwrap().push(x))?;
				r.read_u8().map(|x| self.jumps.as_mut().unwrap().push(x))?;
				r.read_u8()
					.map(|x| self.l_cancel.as_mut().unwrap().push(x))?;
				if version.gte(2, 1) {
					r.read_u8()
						.map(|x| self.hurtbox_state.as_mut().unwrap().push(x))?;
					if version.gte(3, 5) {
						self.velocities.as_mut().unwrap().read_append(r, version)?;
						if version.gte(3, 8) {
							r.read_f32::<BE>()
								.map(|x| self.hitlag.as_mut().unwrap().push(x))?;
							if version.gte(3, 11) {
								r.read_u32::<BE>()
									.map(|x| self.animation_index.as_mut().unwrap().push(x))?;
								if version.gte(3, 16) {
									r.read_u16::<BE>().map(|x| {
										self.last_hit_by_instance.as_mut().unwrap().push(x)
									})?;
									r.read_u16::<BE>()
										.map(|x| self.instance_id.as_mut().unwrap().push(x))?
								}
							}
						}
					}
				}
			}
		};
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::Post {
		immutable::Post {
			character: mem::take(&mut self.character),
			state: mem::take(&mut self.state),
			position: self.position.finish(),
			direction: mem::take(&mut self.direction),
			percent: mem::take(&mut self.percent),
			shield: mem::take(&mut self.shield),
			last_attack_landed: mem::take(&mut self.last_attack_landed),
			combo_count: mem::take(&mut self.combo_count),
			last_hit_by: mem::take(&mut self.last_hit_by),
			stocks: mem::take(&mut self.stocks),
			state_age: mem::take(&mut self.state_age),
			state_flags: self.state_flags.as_mut().map(|x| x.finish()),
			misc_as: mem::take(&mut self.misc_as),
			airborne: mem::take(&mut self.airborne),
			ground: mem::take(&mut self.ground),
			jumps: mem::take(&mut self.jumps),
			l_cancel: mem::take(&mut self.l_cancel),
			hurtbox_state: mem::take(&mut self.hurtbox_state),
			velocities: self.velocities.as_mut().map(|x| x.finish()),
			hitlag: mem::take(&mut self.hitlag),
			animation_index: mem::take(&mut self.animation_index),
			last_hit_by_instance: mem::take(&mut self.last_hit_by_instance),
			instance_id: mem::take(&mut self.instance_id),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Post {
		transpose::Post {
			character: self.character[i],
			state: self.state[i],
			position: self.position.transpose_one(i, version),
			direction: self.direction[i],
			percent: self.percent[i],
			shield: self.shield[i],
			last_attack_landed: self.last_attack_landed[i],
			combo_count: self.combo_count[i],
			last_hit_by: self.last_hit_by[i],
			stocks: self.stocks[i],
			state_age: self.state_age.as_ref().map(|x| x[i]),
			state_flags: self
				.state_flags
				.as_ref()
				.map(|x| x.transpose_one(i, version)),
			misc_as: self.misc_as.as_ref().map(|x| x[i]),
			airborne: self.airborne.as_ref().map(|x| x[i]),
			ground: self.ground.as_ref().map(|x| x[i]),
			jumps: self.jumps.as_ref().map(|x| x[i]),
			l_cancel: self.l_cancel.as_ref().map(|x| x[i]),
			hurtbox_state: self.hurtbox_state.as_ref().map(|x| x[i]),
			velocities: self
				.velocities
				.as_ref()
				.map(|x| x.transpose_one(i, version)),
			hitlag: self.hitlag.as_ref().map(|x| x[i]),
			animation_index: self.animation_index.as_ref().map(|x| x[i]),
			last_hit_by_instance: self.last_hit_by_instance.as_ref().map(|x| x[i]),
			instance_id: self.instance_id.as_ref().map(|x| x[i]),
		}
	}
}

/// Pre-frame update data, required to reconstruct a replay.
///
/// Information is collected right before controller inputs are used to figure out the character’s next action.

pub struct Pre {
	/// Random seed
	pub random_seed: Vec<u32>,
	/// Character’s action state
	pub state: Vec<u16>,
	/// Character’s position
	pub position: Position,
	/// Direction the character is facing
	pub direction: Vec<f32>,
	/// Processed analog joystick position
	pub joystick: Position,
	/// Processed analog c-stick position
	pub cstick: Position,
	/// Processed analog trigger position
	pub triggers: Vec<f32>,
	/// Processed button-state bitmask
	pub buttons: Vec<u32>,
	/// Physical button-state bitmask
	pub buttons_physical: Vec<u16>,
	/// Physical analog trigger positions (useful for IPM)
	pub triggers_physical: TriggersPhysical,
	/// *Added: v1.2* Raw joystick x-position
	pub raw_analog_x: Option<Vec<i8>>,
	/// *Added: v1.4* Damage taken (percent)
	pub percent: Option<Vec<f32>>,
	/// *Added: v3.15* Raw joystick y-position
	pub raw_analog_y: Option<Vec<i8>>,
	/// *Added: v3.17* Raw c-stick x-position
	pub raw_analog_cstick_x: Option<Vec<i8>>,
	/// *Added: v3.17* Raw c-stick y-position
	pub raw_analog_cstick_y: Option<Vec<i8>>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl Pre {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			random_seed: Vec::with_capacity(capacity),
			state: Vec::with_capacity(capacity),
			position: Position::with_capacity(capacity, version),
			direction: Vec::with_capacity(capacity),
			joystick: Position::with_capacity(capacity, version),
			cstick: Position::with_capacity(capacity, version),
			triggers: Vec::with_capacity(capacity),
			buttons: Vec::with_capacity(capacity),
			buttons_physical: Vec::with_capacity(capacity),
			triggers_physical: TriggersPhysical::with_capacity(capacity, version),
			raw_analog_x: version.gte(1, 2).then(|| Vec::with_capacity(capacity)),
			percent: version.gte(1, 4).then(|| Vec::with_capacity(capacity)),
			raw_analog_y: version.gte(3, 15).then(|| Vec::with_capacity(capacity)),
			raw_analog_cstick_x: version.gte(3, 17).then(|| Vec::with_capacity(capacity)),
			raw_analog_cstick_y: version.gte(3, 17).then(|| Vec::with_capacity(capacity)),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.random_seed.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.random_seed.push(0u32);
		self.state.push(0u16);
		self.position.append_default(version);
		self.direction.push(0f32);
		self.joystick.append_default(version);
		self.cstick.append_default(version);
		self.triggers.push(0f32);
		self.buttons.push(0u32);
		self.buttons_physical.push(0u16);
		self.triggers_physical.append_default(version);
		if version.gte(1, 2) {
			self.raw_analog_x.as_mut().unwrap().push(0i8);
			if version.gte(1, 4) {
				self.percent.as_mut().unwrap().push(0f32);
				if version.gte(3, 15) {
					self.raw_analog_y.as_mut().unwrap().push(0i8);
					if version.gte(3, 17) {
						self.raw_analog_cstick_x.as_mut().unwrap().push(0i8);
						self.raw_analog_cstick_y.as_mut().unwrap().push(0i8)
					}
				}
			}
		}
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u32::<BE>().map(|x| self.random_seed.push(x))?;
		r.read_u16::<BE>().map(|x| self.state.push(x))?;
		self.position.read_append(r, version)?;
		r.read_f32::<BE>().map(|x| self.direction.push(x))?;
		self.joystick.read_append(r, version)?;
		self.cstick.read_append(r, version)?;
		r.read_f32::<BE>().map(|x| self.triggers.push(x))?;
		r.read_u32::<BE>().map(|x| self.buttons.push(x))?;
		r.read_u16::<BE>().map(|x| self.buttons_physical.push(x))?;
		self.triggers_physical.read_append(r, version)?;
		if version.gte(1, 2) {
			r.read_i8()
				.map(|x| self.raw_analog_x.as_mut().unwrap().push(x))?;
			if version.gte(1, 4) {
				r.read_f32::<BE>()
					.map(|x| self.percent.as_mut().unwrap().push(x))?;
				if version.gte(3, 15) {
					r.read_i8()
						.map(|x| self.raw_analog_y.as_mut().unwrap().push(x))?;
					if version.gte(3, 17) {
						r.read_i8()
							.map(|x| self.raw_analog_cstick_x.as_mut().unwrap().push(x))?;
						r.read_i8()
							.map(|x| self.raw_analog_cstick_y.as_mut().unwrap().push(x))?
					}
				}
			}
		};
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::Pre {
		immutable::Pre {
			random_seed: mem::take(&mut self.random_seed),
			state: mem::take(&mut self.state),
			position: self.position.finish(),
			direction: mem::take(&mut self.direction),
			joystick: self.joystick.finish(),
			cstick: self.cstick.finish(),
			triggers: mem::take(&mut self.triggers),
			buttons: mem::take(&mut self.buttons),
			buttons_physical: mem::take(&mut self.buttons_physical),
			triggers_physical: self.triggers_physical.finish(),
			raw_analog_x: mem::take(&mut self.raw_analog_x),
			percent: mem::take(&mut self.percent),
			raw_analog_y: mem::take(&mut self.raw_analog_y),
			raw_analog_cstick_x: mem::take(&mut self.raw_analog_cstick_x),
			raw_analog_cstick_y: mem::take(&mut self.raw_analog_cstick_y),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Pre {
		transpose::Pre {
			random_seed: self.random_seed[i],
			state: self.state[i],
			position: self.position.transpose_one(i, version),
			direction: self.direction[i],
			joystick: self.joystick.transpose_one(i, version),
			cstick: self.cstick.transpose_one(i, version),
			triggers: self.triggers[i],
			buttons: self.buttons[i],
			buttons_physical: self.buttons_physical[i],
			triggers_physical: self.triggers_physical.transpose_one(i, version),
			raw_analog_x: self.raw_analog_x.as_ref().map(|x| x[i]),
			percent: self.percent.as_ref().map(|x| x[i]),
			raw_analog_y: self.raw_analog_y.as_ref().map(|x| x[i]),
			raw_analog_cstick_x: self.raw_analog_cstick_x.as_ref().map(|x| x[i]),
			raw_analog_cstick_y: self.raw_analog_cstick_y.as_ref().map(|x| x[i]),
		}
	}
}

/// This event only occurs on Pokemon Stadium, and is sent whenever the transformation event or transformation type changes.

pub struct StadiumTransformation {
	/// The subevent for each transformation. (2 = Initialize, 3 = On monitor, 4 = Previous transformation receding, 5 = New transformation rising, 6 = Finalize, 0 = Finished)
	pub event: Vec<u16>,
	/// The current or upcoming transformation. (3 = Fire, 4 = Grass, 5 = Normal, 6 = Rock, 9 = Water)
	pub r#type: Vec<u16>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl StadiumTransformation {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			event: Vec::with_capacity(capacity),
			r#type: Vec::with_capacity(capacity),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.event.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.event.push(0u16);
		self.r#type.push(0u16)
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u16::<BE>().map(|x| self.event.push(x))?;
		r.read_u16::<BE>().map(|x| self.r#type.push(x))?;
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::StadiumTransformation {
		immutable::StadiumTransformation {
			event: mem::take(&mut self.event),
			r#type: mem::take(&mut self.r#type),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::StadiumTransformation {
		transpose::StadiumTransformation {
			event: self.event[i],
			r#type: self.r#type[i],
		}
	}
}

/// Initialization data such as game mode, settings, characters & stage.

pub struct Start {
	/// Random seed
	pub random_seed: Vec<u32>,
	/// *Added: v3.10* Scene frame counter. Starts at 0, and increments every frame (even when paused)
	pub scene_frame_counter: Option<Vec<u32>>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl Start {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			random_seed: Vec::with_capacity(capacity),
			scene_frame_counter: version.gte(3, 10).then(|| Vec::with_capacity(capacity)),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.random_seed.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.random_seed.push(0u32);
		if version.gte(3, 10) {
			self.scene_frame_counter.as_mut().unwrap().push(0u32)
		}
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u32::<BE>().map(|x| self.random_seed.push(x))?;
		if version.gte(3, 10) {
			r.read_u32::<BE>()
				.map(|x| self.scene_frame_counter.as_mut().unwrap().push(x))?
		};
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::Start {
		immutable::Start {
			random_seed: mem::take(&mut self.random_seed),
			scene_frame_counter: mem::take(&mut self.scene_frame_counter),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Start {
		transpose::Start {
			random_seed: self.random_seed[i],
			scene_frame_counter: self.scene_frame_counter.as_ref().map(|x| x[i]),
		}
	}
}

/// Miscellaneous state flags.

pub struct StateFlags(
	pub Vec<u8>,
	pub Vec<u8>,
	pub Vec<u8>,
	pub Vec<u8>,
	pub Vec<u8>,
);

impl StateFlags {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self(
			Vec::with_capacity(capacity),
			Vec::with_capacity(capacity),
			Vec::with_capacity(capacity),
			Vec::with_capacity(capacity),
			Vec::with_capacity(capacity),
		)
	}

	pub fn len(&self) -> usize {
		self.0.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.0.push(0u8);
		self.1.push(0u8);
		self.2.push(0u8);
		self.3.push(0u8);
		self.4.push(0u8)
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u8().map(|x| self.0.push(x))?;
		r.read_u8().map(|x| self.1.push(x))?;
		r.read_u8().map(|x| self.2.push(x))?;
		r.read_u8().map(|x| self.3.push(x))?;
		r.read_u8().map(|x| self.4.push(x))?;
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::StateFlags {
		immutable::StateFlags(
			mem::take(&mut self.0),
			mem::take(&mut self.1),
			mem::take(&mut self.2),
			mem::take(&mut self.3),
			mem::take(&mut self.4),
		)
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::StateFlags {
		transpose::StateFlags(self.0[i], self.1[i], self.2[i], self.3[i], self.4[i])
	}
}

/// Trigger state.

pub struct TriggersPhysical {
	pub l: Vec<f32>,
	pub r: Vec<f32>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl TriggersPhysical {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			l: Vec::with_capacity(capacity),
			r: Vec::with_capacity(capacity),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.l.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.l.push(0f32);
		self.r.push(0f32)
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_f32::<BE>().map(|x| self.l.push(x))?;
		r.read_f32::<BE>().map(|x| self.r.push(x))?;
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::TriggersPhysical {
		immutable::TriggersPhysical {
			l: mem::take(&mut self.l),
			r: mem::take(&mut self.r),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::TriggersPhysical {
		transpose::TriggersPhysical {
			l: self.l[i],
			r: self.r[i],
		}
	}
}

/// Self-induced and knockback velocities.

pub struct Velocities {
	/// Self-induced x-velocity (airborne)
	pub self_x_air: Vec<f32>,
	/// Self-induced y-velocity
	pub self_y: Vec<f32>,
	/// Knockback-induced x-velocity
	pub knockback_x: Vec<f32>,
	/// Knockback-induced y-velocity
	pub knockback_y: Vec<f32>,
	/// Self-induced x-velocity (grounded)
	pub self_x_ground: Vec<f32>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl Velocities {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			self_x_air: Vec::with_capacity(capacity),
			self_y: Vec::with_capacity(capacity),
			knockback_x: Vec::with_capacity(capacity),
			knockback_y: Vec::with_capacity(capacity),
			self_x_ground: Vec::with_capacity(capacity),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.self_x_air.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.self_x_air.push(0f32);
		self.self_y.push(0f32);
		self.knockback_x.push(0f32);
		self.knockback_y.push(0f32);
		self.self_x_ground.push(0f32)
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_f32::<BE>().map(|x| self.self_x_air.push(x))?;
		r.read_f32::<BE>().map(|x| self.self_y.push(x))?;
		r.read_f32::<BE>().map(|x| self.knockback_x.push(x))?;
		r.read_f32::<BE>().map(|x| self.knockback_y.push(x))?;
		r.read_f32::<BE>().map(|x| self.self_x_ground.push(x))?;
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::Velocities {
		immutable::Velocities {
			self_x_air: mem::take(&mut self.self_x_air),
			self_y: mem::take(&mut self.self_y),
			knockback_x: mem::take(&mut self.knockback_x),
			knockback_y: mem::take(&mut self.knockback_y),
			self_x_ground: mem::take(&mut self.self_x_ground),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Velocities {
		transpose::Velocities {
			self_x_air: self.self_x_air[i],
			self_y: self.self_y[i],
			knockback_x: self.knockback_x[i],
			knockback_y: self.knockback_y[i],
			self_x_ground: self.self_x_ground[i],
		}
	}
}

/// 2D velocity.

pub struct Velocity {
	pub x: Vec<f32>,
	pub y: Vec<f32>,
	/// Indicates which indexes are valid. Invalid indexes can occur on frames where a character is absent (ICs or 2v2 games)
	pub validity: NullBufferBuilder,
}

impl Velocity {
	fn with_capacity(capacity: usize, version: Version) -> Self {
		Self {
			x: Vec::with_capacity(capacity),
			y: Vec::with_capacity(capacity),
			validity: NullBufferBuilder::new(capacity),
		}
	}

	pub fn len(&self) -> usize {
		self.x.len()
	}

	pub fn append_default(&mut self, version: Version) {
		self.validity.append_non_null();
		self.x.push(0f32);
		self.y.push(0f32)
	}

	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_f32::<BE>().map(|x| self.x.push(x))?;
		r.read_f32::<BE>().map(|x| self.y.push(x))?;
		self.validity.append_non_null();
		Ok(())
	}

	pub fn finish(&mut self) -> immutable::Velocity {
		immutable::Velocity {
			x: mem::take(&mut self.x),
			y: mem::take(&mut self.y),
			validity: self.validity.finish(),
		}
	}

	pub fn transpose_one(&self, i: usize, version: Version) -> transpose::Velocity {
		transpose::Velocity {
			x: self.x[i],
			y: self.y[i],
		}
	}
}
