// This file is auto-generated by `gen/scripts/frames`. Do not edit.

#![allow(unused_variables)]

use std::{
	io::{Result, Write},
	mem::size_of,
};

use byteorder::{ReadBytesExt, WriteBytesExt};

use crate::{
	frame::{Data, Frame, Frames, Port, PortData, PortOccupancy, Reader, Writer},
	io::slippi::{de::Event, Version},
};

type BE = byteorder::BigEndian;

impl Data {
	fn write_pre<W: Write>(
		&self,
		w: &mut W,
		version: Version,
		idx: usize,
		frame_id: i32,
		occ: PortOccupancy,
	) -> Result<()> {
		if self.validity.is_valid(idx) {
			w.write_u8(Event::FramePre as u8)?;
			w.write_i32::<BE>(frame_id)?;
			w.write_u8(occ.port as u8)?;
			w.write_u8(match occ.follower {
				true => 1,
				_ => 0,
			})?;
			self.pre.write(w, version, idx)?;
		}
		Ok(())
	}

	fn write_post<W: Write>(
		&self,
		w: &mut W,
		version: Version,
		idx: usize,
		frame_id: i32,
		occ: PortOccupancy,
	) -> Result<()> {
		if self.validity.is_valid(idx) {
			w.write_u8(Event::FramePost as u8)?;
			w.write_i32::<BE>(frame_id)?;
			w.write_u8(occ.port as u8)?;
			w.write_u8(match occ.follower {
				true => 1,
				_ => 0,
			})?;
			self.post.write(w, version, idx)?;
		}
		Ok(())
	}
}

impl PortData {
	fn write_pre<W: Write>(
		&self,
		w: &mut W,
		version: Version,
		idx: usize,
		frame_id: i32,
	) -> Result<()> {
		if self.validity.is_valid(idx) {
			self.leader.write_pre(
				w,
				version,
				idx,
				frame_id,
				PortOccupancy {
					port: self.port,
					follower: false,
				},
			)?;
			self.follower.as_ref().map_or(Ok(()), |f| {
				if f.validity.is_valid(idx) {
					f.write_pre(
						w,
						version,
						idx,
						frame_id,
						PortOccupancy {
							port: self.port,
							follower: true,
						},
					)
				} else {
					Ok(())
				}
			})
		} else {
			Ok(())
		}
	}

	fn write_post<W: Write>(
		&self,
		w: &mut W,
		version: Version,
		idx: usize,
		frame_id: i32,
	) -> Result<()> {
		if self.validity.is_valid(idx) {
			self.leader.write_post(
				w,
				version,
				idx,
				frame_id,
				PortOccupancy {
					port: self.port,
					follower: false,
				},
			)?;
			self.follower.as_ref().map_or(Ok(()), |f| {
				if f.validity.is_valid(idx) {
					f.write_post(
						w,
						version,
						idx,
						frame_id,
						PortOccupancy {
							port: self.port,
							follower: true,
						},
					)
				} else {
					Ok(())
				}
			})
		} else {
			Ok(())
		}
	}
}

impl Writer for Frame {
	fn write<W: Write>(&self, w: &mut W, version: Version) -> Result<()> {
		for (idx, &frame_id) in self.id.iter().enumerate() {
			if version.gte(2, 2) {
				w.write_u8(Event::FrameStart as u8)?;
				w.write_i32::<BE>(frame_id)?;
				self.start.as_ref().unwrap().write(w, version, idx)?;
			}
			for port in &self.ports {
				port.write_pre(w, version, idx, frame_id)?;
			}
			if version.gte(3, 18) {
				// FOD platform
				let offset = self.fod_platform_offset.as_ref().unwrap();
				for evt_idx in (offset[idx] as usize)..(offset[idx + 1] as usize) {
					w.write_u8(Event::FodPlatform as u8)?;
					w.write_i32::<BE>(frame_id)?;
					self.fod_platform
						.as_ref()
						.unwrap()
						.write(w, version, evt_idx)?;
				}

				// Dreamland Whispy
				let offset = self.dreamland_whispy_offset.as_ref().unwrap();
				for evt_idx in (offset[idx] as usize)..(offset[idx + 1] as usize) {
					w.write_u8(Event::DreamlandWhispy as u8)?;
					w.write_i32::<BE>(frame_id)?;
					self.dreamland_whispy
						.as_ref()
						.unwrap()
						.write(w, version, evt_idx)?;
				}

				// Stadium transformation
				let offset = self.stadium_transformation_offset.as_ref().unwrap();
				for evt_idx in (offset[idx] as usize)..(offset[idx + 1] as usize) {
					w.write_u8(Event::StadiumTransformation as u8)?;
					w.write_i32::<BE>(frame_id)?;
					self.stadium_transformation
						.as_ref()
						.unwrap()
						.write(w, version, evt_idx)?;
				}
			}
			if version.gte(3, 0) {
				let offset = self.item_offset.as_ref().unwrap();
				for item_idx in (offset[idx] as usize)..(offset[idx + 1] as usize) {
					w.write_u8(Event::Item as u8)?;
					w.write_i32::<BE>(frame_id)?;
					self.item.as_ref().unwrap().write(w, version, item_idx)?;
				}
			}
			for port in &self.ports {
				port.write_post(w, version, idx, frame_id)?;
			}
			if version.gte(3, 0) {
				w.write_u8(Event::FrameEnd as u8)?;
				w.write_i32::<BE>(frame_id)?;
				self.end.as_ref().unwrap().write(w, version, idx)?;
			}
		}
		Ok(())
	}
}

impl Reader for Frame {
	fn open(&mut self, version: Version, id: i32, port_count: usize) {
		self.id.push(id);
	}

	fn close(&mut self, version: Version, port_count: usize) {
		let len = self.len();
		for p in &mut self.ports {
			while p.len() < len {
				p.append_null(version);
			}
			if let Some(f) = &mut p.follower {
				while f.len() < len {
					f.append_null(version);
				}
			}
		}

		if version.gte(3, 0) {
			self.item_offset
				.as_mut()
				.unwrap()
				.push(self.item.as_ref().unwrap().id.len().try_into().unwrap());

			if version.gte(3, 18) {
				self.fod_platform_offset.as_mut().unwrap().push(
					self.fod_platform
						.as_ref()
						.unwrap()
						.platform
						.len()
						.try_into()
						.unwrap(),
				);
				self.dreamland_whispy_offset.as_mut().unwrap().push(
					self.dreamland_whispy
						.as_ref()
						.unwrap()
						.direction
						.len()
						.try_into()
						.unwrap(),
				);
				self.stadium_transformation_offset.as_mut().unwrap().push(
					self.stadium_transformation
						.as_ref()
						.unwrap()
						.event
						.len()
						.try_into()
						.unwrap(),
				);
			}
		}
	}

	fn read_start(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.start.as_mut().unwrap().read_append(r, version)
	}

	fn read_pre(
		&mut self,
		r: &mut &[u8],
		version: Version,
		id: i32,
		port_index: u8,
		port: Port,
		follower: bool,
	) -> Result<()> {
		let port_data = &mut self.ports[port_index as usize];
		if !follower {
			port_data.validity.push(true);
		}
		let character = match follower {
			true => port_data.follower.as_mut().unwrap(),
			_ => &mut port_data.leader,
		};
		character.validity.push(true);
		character.pre.read_append(r, version)
	}

	fn read_post(
		&mut self,
		r: &mut &[u8],
		version: Version,
		id: i32,
		port_index: u8,
		port: Port,
		follower: bool,
	) -> Result<()> {
		let port_data = &mut self.ports[port_index as usize];
		let character = match follower {
			true => port_data.follower.as_mut().unwrap(),
			_ => &mut port_data.leader,
		};
		character.post.read_append(r, version)
	}

	fn read_item(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.item.as_mut().unwrap().read_append(r, version)
	}

	fn read_fod_platform(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.fod_platform.as_mut().unwrap().read_append(r, version)
	}

	fn read_dreamland_whispy(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.dreamland_whispy
			.as_mut()
			.unwrap()
			.read_append(r, version)
	}

	fn read_stadium_transformation(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.stadium_transformation
			.as_mut()
			.unwrap()
			.read_append(r, version)
	}

	fn read_end(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.end.as_mut().unwrap().read_append(r, version)
	}
}

use crate::frame::DreamlandWhispy;

impl DreamlandWhispy {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.direction.push(r.read_u8()?);
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u8(self.direction[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u8>();
		size
	}
}

use crate::frame::End;

impl End {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		if version.gte(3, 7) {
			self.latest_finalized_frame
				.as_mut()
				.unwrap()
				.push(r.read_i32::<BE>()?)
		};
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		if version.gte(3, 7) {
			w.write_i32::<BE>(self.latest_finalized_frame.as_ref().unwrap()[i])?
		};
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		if version.gte(3, 7) {
			size += size_of::<i32>()
		};
		size
	}
}

use crate::frame::FodPlatform;

impl FodPlatform {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.platform.push(r.read_u8()?);
		self.height.push(r.read_f32::<BE>()?);
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u8(self.platform[i])?;
		w.write_f32::<BE>(self.height[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u8>();
		size += size_of::<f32>();
		size
	}
}

use crate::frame::Item;

impl Item {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.r#type.push(r.read_u16::<BE>()?);
		self.state.push(r.read_u8()?);
		self.direction.push(r.read_f32::<BE>()?);
		self.velocity.read_append(r, version)?;
		self.position.read_append(r, version)?;
		self.damage.push(r.read_u16::<BE>()?);
		self.timer.push(r.read_f32::<BE>()?);
		self.id.push(r.read_u32::<BE>()?);
		if version.gte(3, 2) {
			self.misc.as_mut().unwrap().read_append(r, version)?;
			if version.gte(3, 6) {
				self.owner.as_mut().unwrap().push(r.read_i8()?);
				if version.gte(3, 16) {
					self.instance_id.as_mut().unwrap().push(r.read_u16::<BE>()?)
				}
			}
		};
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u16::<BE>(self.r#type[i])?;
		w.write_u8(self.state[i])?;
		w.write_f32::<BE>(self.direction[i])?;
		self.velocity.write(w, version, i)?;
		self.position.write(w, version, i)?;
		w.write_u16::<BE>(self.damage[i])?;
		w.write_f32::<BE>(self.timer[i])?;
		w.write_u32::<BE>(self.id[i])?;
		if version.gte(3, 2) {
			self.misc.as_ref().unwrap().write(w, version, i)?;
			if version.gte(3, 6) {
				w.write_i8(self.owner.as_ref().unwrap()[i])?;
				if version.gte(3, 16) {
					w.write_u16::<BE>(self.instance_id.as_ref().unwrap()[i])?
				}
			}
		};
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u16>();
		size += size_of::<u8>();
		size += size_of::<f32>();
		size += Velocity::size(version);
		size += Position::size(version);
		size += size_of::<u16>();
		size += size_of::<f32>();
		size += size_of::<u32>();
		if version.gte(3, 2) {
			size += ItemMisc::size(version);
			if version.gte(3, 6) {
				size += size_of::<i8>();
				if version.gte(3, 16) {
					size += size_of::<u16>()
				}
			}
		};
		size
	}
}

use crate::frame::ItemMisc;

impl ItemMisc {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.0.push(r.read_u8()?);
		self.1.push(r.read_u8()?);
		self.2.push(r.read_u8()?);
		self.3.push(r.read_u8()?);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u8(self.0[i])?;
		w.write_u8(self.1[i])?;
		w.write_u8(self.2[i])?;
		w.write_u8(self.3[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size
	}
}

use crate::frame::Position;

impl Position {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.x.push(r.read_f32::<BE>()?);
		self.y.push(r.read_f32::<BE>()?);
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_f32::<BE>(self.x[i])?;
		w.write_f32::<BE>(self.y[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<f32>();
		size += size_of::<f32>();
		size
	}
}

use crate::frame::Post;

impl Post {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.character.push(r.read_u8()?);
		self.state.push(r.read_u16::<BE>()?);
		self.position.read_append(r, version)?;
		self.direction.push(r.read_f32::<BE>()?);
		self.percent.push(r.read_f32::<BE>()?);
		self.shield.push(r.read_f32::<BE>()?);
		self.last_attack_landed.push(r.read_u8()?);
		self.combo_count.push(r.read_u8()?);
		self.last_hit_by.push(r.read_u8()?);
		self.stocks.push(r.read_u8()?);
		if version.gte(0, 2) {
			self.state_age.as_mut().unwrap().push(r.read_f32::<BE>()?);
			if version.gte(2, 0) {
				self.state_flags.as_mut().unwrap().read_append(r, version)?;
				self.misc_as.as_mut().unwrap().push(r.read_f32::<BE>()?);
				self.airborne.as_mut().unwrap().push(r.read_u8()?);
				self.ground.as_mut().unwrap().push(r.read_u16::<BE>()?);
				self.jumps.as_mut().unwrap().push(r.read_u8()?);
				self.l_cancel.as_mut().unwrap().push(r.read_u8()?);
				if version.gte(2, 1) {
					self.hurtbox_state.as_mut().unwrap().push(r.read_u8()?);
					if version.gte(3, 5) {
						self.velocities.as_mut().unwrap().read_append(r, version)?;
						if version.gte(3, 8) {
							self.hitlag.as_mut().unwrap().push(r.read_f32::<BE>()?);
							if version.gte(3, 11) {
								self.animation_index
									.as_mut()
									.unwrap()
									.push(r.read_u32::<BE>()?);
								if version.gte(3, 16) {
									self.last_hit_by_instance
										.as_mut()
										.unwrap()
										.push(r.read_u16::<BE>()?);
									self.instance_id.as_mut().unwrap().push(r.read_u16::<BE>()?)
								}
							}
						}
					}
				}
			}
		};
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u8(self.character[i])?;
		w.write_u16::<BE>(self.state[i])?;
		self.position.write(w, version, i)?;
		w.write_f32::<BE>(self.direction[i])?;
		w.write_f32::<BE>(self.percent[i])?;
		w.write_f32::<BE>(self.shield[i])?;
		w.write_u8(self.last_attack_landed[i])?;
		w.write_u8(self.combo_count[i])?;
		w.write_u8(self.last_hit_by[i])?;
		w.write_u8(self.stocks[i])?;
		if version.gte(0, 2) {
			w.write_f32::<BE>(self.state_age.as_ref().unwrap()[i])?;
			if version.gte(2, 0) {
				self.state_flags.as_ref().unwrap().write(w, version, i)?;
				w.write_f32::<BE>(self.misc_as.as_ref().unwrap()[i])?;
				w.write_u8(self.airborne.as_ref().unwrap()[i])?;
				w.write_u16::<BE>(self.ground.as_ref().unwrap()[i])?;
				w.write_u8(self.jumps.as_ref().unwrap()[i])?;
				w.write_u8(self.l_cancel.as_ref().unwrap()[i])?;
				if version.gte(2, 1) {
					w.write_u8(self.hurtbox_state.as_ref().unwrap()[i])?;
					if version.gte(3, 5) {
						self.velocities.as_ref().unwrap().write(w, version, i)?;
						if version.gte(3, 8) {
							w.write_f32::<BE>(self.hitlag.as_ref().unwrap()[i])?;
							if version.gte(3, 11) {
								w.write_u32::<BE>(self.animation_index.as_ref().unwrap()[i])?;
								if version.gte(3, 16) {
									w.write_u16::<BE>(
										self.last_hit_by_instance.as_ref().unwrap()[i],
									)?;
									w.write_u16::<BE>(self.instance_id.as_ref().unwrap()[i])?
								}
							}
						}
					}
				}
			}
		};
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u8>();
		size += size_of::<u16>();
		size += Position::size(version);
		size += size_of::<f32>();
		size += size_of::<f32>();
		size += size_of::<f32>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		if version.gte(0, 2) {
			size += size_of::<f32>();
			if version.gte(2, 0) {
				size += StateFlags::size(version);
				size += size_of::<f32>();
				size += size_of::<u8>();
				size += size_of::<u16>();
				size += size_of::<u8>();
				size += size_of::<u8>();
				if version.gte(2, 1) {
					size += size_of::<u8>();
					if version.gte(3, 5) {
						size += Velocities::size(version);
						if version.gte(3, 8) {
							size += size_of::<f32>();
							if version.gte(3, 11) {
								size += size_of::<u32>();
								if version.gte(3, 16) {
									size += size_of::<u16>();
									size += size_of::<u16>()
								}
							}
						}
					}
				}
			}
		};
		size
	}
}

use crate::frame::Pre;

impl Pre {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.random_seed.push(r.read_u32::<BE>()?);
		self.state.push(r.read_u16::<BE>()?);
		self.position.read_append(r, version)?;
		self.direction.push(r.read_f32::<BE>()?);
		self.joystick.read_append(r, version)?;
		self.cstick.read_append(r, version)?;
		self.triggers.push(r.read_f32::<BE>()?);
		self.buttons.push(r.read_u32::<BE>()?);
		self.buttons_physical.push(r.read_u16::<BE>()?);
		self.triggers_physical.read_append(r, version)?;
		if version.gte(1, 2) {
			self.raw_analog_x.as_mut().unwrap().push(r.read_i8()?);
			if version.gte(1, 4) {
				self.percent.as_mut().unwrap().push(r.read_f32::<BE>()?);
				if version.gte(3, 15) {
					self.raw_analog_y.as_mut().unwrap().push(r.read_i8()?);
					if version.gte(3, 17) {
						self.raw_analog_cstick_x
							.as_mut()
							.unwrap()
							.push(r.read_i8()?);
						self.raw_analog_cstick_y
							.as_mut()
							.unwrap()
							.push(r.read_i8()?)
					}
				}
			}
		};
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u32::<BE>(self.random_seed[i])?;
		w.write_u16::<BE>(self.state[i])?;
		self.position.write(w, version, i)?;
		w.write_f32::<BE>(self.direction[i])?;
		self.joystick.write(w, version, i)?;
		self.cstick.write(w, version, i)?;
		w.write_f32::<BE>(self.triggers[i])?;
		w.write_u32::<BE>(self.buttons[i])?;
		w.write_u16::<BE>(self.buttons_physical[i])?;
		self.triggers_physical.write(w, version, i)?;
		if version.gte(1, 2) {
			w.write_i8(self.raw_analog_x.as_ref().unwrap()[i])?;
			if version.gte(1, 4) {
				w.write_f32::<BE>(self.percent.as_ref().unwrap()[i])?;
				if version.gte(3, 15) {
					w.write_i8(self.raw_analog_y.as_ref().unwrap()[i])?;
					if version.gte(3, 17) {
						w.write_i8(self.raw_analog_cstick_x.as_ref().unwrap()[i])?;
						w.write_i8(self.raw_analog_cstick_y.as_ref().unwrap()[i])?
					}
				}
			}
		};
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u32>();
		size += size_of::<u16>();
		size += Position::size(version);
		size += size_of::<f32>();
		size += Position::size(version);
		size += Position::size(version);
		size += size_of::<f32>();
		size += size_of::<u32>();
		size += size_of::<u16>();
		size += TriggersPhysical::size(version);
		if version.gte(1, 2) {
			size += size_of::<i8>();
			if version.gte(1, 4) {
				size += size_of::<f32>();
				if version.gte(3, 15) {
					size += size_of::<i8>();
					if version.gte(3, 17) {
						size += size_of::<i8>();
						size += size_of::<i8>()
					}
				}
			}
		};
		size
	}
}

use crate::frame::StadiumTransformation;

impl StadiumTransformation {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.event.push(r.read_u16::<BE>()?);
		self.r#type.push(r.read_u16::<BE>()?);
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u16::<BE>(self.event[i])?;
		w.write_u16::<BE>(self.r#type[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u16>();
		size += size_of::<u16>();
		size
	}
}

use crate::frame::Start;

impl Start {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.random_seed.push(r.read_u32::<BE>()?);
		if version.gte(3, 10) {
			self.scene_frame_counter
				.as_mut()
				.unwrap()
				.push(r.read_u32::<BE>()?)
		};
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u32::<BE>(self.random_seed[i])?;
		if version.gte(3, 10) {
			w.write_u32::<BE>(self.scene_frame_counter.as_ref().unwrap()[i])?
		};
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u32>();
		if version.gte(3, 10) {
			size += size_of::<u32>()
		};
		size
	}
}

use crate::frame::StateFlags;

impl StateFlags {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.0.push(r.read_u8()?);
		self.1.push(r.read_u8()?);
		self.2.push(r.read_u8()?);
		self.3.push(r.read_u8()?);
		self.4.push(r.read_u8()?);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u8(self.0[i])?;
		w.write_u8(self.1[i])?;
		w.write_u8(self.2[i])?;
		w.write_u8(self.3[i])?;
		w.write_u8(self.4[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size
	}
}

use crate::frame::TriggersPhysical;

impl TriggersPhysical {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.l.push(r.read_f32::<BE>()?);
		self.r.push(r.read_f32::<BE>()?);
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_f32::<BE>(self.l[i])?;
		w.write_f32::<BE>(self.r[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<f32>();
		size += size_of::<f32>();
		size
	}
}

use crate::frame::Velocities;

impl Velocities {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.self_x_air.push(r.read_f32::<BE>()?);
		self.self_y.push(r.read_f32::<BE>()?);
		self.knockback_x.push(r.read_f32::<BE>()?);
		self.knockback_y.push(r.read_f32::<BE>()?);
		self.self_x_ground.push(r.read_f32::<BE>()?);
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_f32::<BE>(self.self_x_air[i])?;
		w.write_f32::<BE>(self.self_y[i])?;
		w.write_f32::<BE>(self.knockback_x[i])?;
		w.write_f32::<BE>(self.knockback_y[i])?;
		w.write_f32::<BE>(self.self_x_ground[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<f32>();
		size += size_of::<f32>();
		size += size_of::<f32>();
		size += size_of::<f32>();
		size += size_of::<f32>();
		size
	}
}

use crate::frame::Velocity;

impl Velocity {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		self.x.push(r.read_f32::<BE>()?);
		self.y.push(r.read_f32::<BE>()?);
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_f32::<BE>(self.x[i])?;
		w.write_f32::<BE>(self.y[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<f32>();
		size += size_of::<f32>();
		size
	}
}
