// This file is auto-generated by `gen/scripts/frames`. Do not edit.

#![allow(unused_variables)]

use std::{
	io::{Result, Write},
	mem::size_of,
};

use byteorder::{ReadBytesExt, WriteBytesExt};

use crate::{
	frame::{Data, Frame, PortData, PortOccupancy},
	io::slippi::{Version, de::Event},
};

type BE = byteorder::BigEndian;

impl Data {
	fn write_pre<W: Write>(
		&self,
		w: &mut W,
		version: Version,
		idx: usize,
		frame_id: i32,
		port: PortOccupancy,
	) -> Result<()> {
		if self.validity.is_valid(idx) {
			w.write_u8(Event::FramePre as u8)?;
			w.write_i32::<BE>(frame_id)?;
			w.write_u8(port.port as u8)?;
			w.write_u8(match port.follower {
				true => 1,
				_ => 0,
			})?;
			self.pre.write(w, version, idx)?;
		}
		Ok(())
	}

	fn write_post<W: Write>(
		&self,
		w: &mut W,
		version: Version,
		idx: usize,
		frame_id: i32,
		port: PortOccupancy,
	) -> Result<()> {
		if self.validity.is_valid(idx) {
			w.write_u8(Event::FramePost as u8)?;
			w.write_i32::<BE>(frame_id)?;
			w.write_u8(port.port as u8)?;
			w.write_u8(match port.follower {
				true => 1,
				_ => 0,
			})?;
			self.post.write(w, version, idx)?;
		}
		Ok(())
	}
}

impl PortData {
	fn write_pre<W: Write>(
		&self,
		w: &mut W,
		version: Version,
		idx: usize,
		frame_id: i32,
	) -> Result<()> {
		self.leader.write_pre(
			w,
			version,
			idx,
			frame_id,
			PortOccupancy {
				port: self.port,
				follower: false,
			},
		)?;
		self.follower.as_ref().map_or(Ok(()), |f| {
			if f.validity.is_valid(idx) {
				f.write_pre(
					w,
					version,
					idx,
					frame_id,
					PortOccupancy {
						port: self.port,
						follower: true,
					},
				)
			} else {
				Ok(())
			}
		})
	}

	fn write_post<W: Write>(
		&self,
		w: &mut W,
		version: Version,
		idx: usize,
		frame_id: i32,
	) -> Result<()> {
		self.leader.write_post(
			w,
			version,
			idx,
			frame_id,
			PortOccupancy {
				port: self.port,
				follower: false,
			},
		)?;
		self.follower.as_ref().map_or(Ok(()), |f| {
			if f.validity.is_valid(idx) {
				f.write_post(
					w,
					version,
					idx,
					frame_id,
					PortOccupancy {
						port: self.port,
						follower: true,
					},
				)
			} else {
				Ok(())
			}
		})
	}
}

impl Frame {
	pub fn write<W: Write>(&self, w: &mut W, version: Version) -> Result<()> {
		for (idx, &frame_id) in self.id.iter().enumerate() {
			if version.gte(2, 2) {
				w.write_u8(Event::FrameStart as u8)?;
				w.write_i32::<BE>(frame_id)?;
				self.start.as_ref().unwrap().write(w, version, idx)?;
			}
			for port in &self.ports {
				port.write_pre(w, version, idx, frame_id)?;
			}
			if version.gte(3, 18) {
				// FOD platform
				let offset = self.fod_platform_offset.as_ref().unwrap();
				for evt_idx in (offset[idx] as usize)..(offset[idx + 1] as usize) {
					w.write_u8(Event::FodPlatform as u8)?;
					w.write_i32::<BE>(frame_id)?;
					self.fod_platform
						.as_ref()
						.unwrap()
						.write(w, version, evt_idx)?;
				}

				// Dreamland Whispy
				let offset = self.dreamland_whispy_offset.as_ref().unwrap();
				for evt_idx in (offset[idx] as usize)..(offset[idx + 1] as usize) {
					w.write_u8(Event::DreamlandWhispy as u8)?;
					w.write_i32::<BE>(frame_id)?;
					self.dreamland_whispy
						.as_ref()
						.unwrap()
						.write(w, version, evt_idx)?;
				}

				// Stadium transformation
				let offset = self.stadium_transformation_offset.as_ref().unwrap();
				for evt_idx in (offset[idx] as usize)..(offset[idx + 1] as usize) {
					w.write_u8(Event::StadiumTransformation as u8)?;
					w.write_i32::<BE>(frame_id)?;
					self.stadium_transformation
						.as_ref()
						.unwrap()
						.write(w, version, evt_idx)?;
				}
			}
			if version.gte(3, 0) {
				let offset = self.item_offset.as_ref().unwrap();
				for item_idx in (offset[idx] as usize)..(offset[idx + 1] as usize) {
					w.write_u8(Event::Item as u8)?;
					w.write_i32::<BE>(frame_id)?;
					self.item.as_ref().unwrap().write(w, version, item_idx)?;
				}
			}
			for port in &self.ports {
				port.write_post(w, version, idx, frame_id)?;
			}
			if version.gte(3, 0) {
				w.write_u8(Event::FrameEnd as u8)?;
				w.write_i32::<BE>(frame_id)?;
				self.end.as_ref().unwrap().write(w, version, idx)?;
			}
		}
		Ok(())
	}
}

use crate::frame::DreamlandWhispy;

impl DreamlandWhispy {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u8().map(|x| self.direction.push(x))?;
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u8(self.direction[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u8>();
		size
	}
}

use crate::frame::End;

impl End {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		if version.gte(3, 7) {
			r.read_i32::<BE>()
				.map(|x| self.latest_finalized_frame.as_mut().unwrap().push(x))?
		};
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		if version.gte(3, 7) {
			w.write_i32::<BE>(self.latest_finalized_frame.as_ref().unwrap()[i])?
		};
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		if version.gte(3, 7) {
			size += size_of::<i32>()
		};
		size
	}
}

use crate::frame::FodPlatform;

impl FodPlatform {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u8().map(|x| self.platform.push(x))?;
		r.read_f32::<BE>().map(|x| self.height.push(x))?;
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u8(self.platform[i])?;
		w.write_f32::<BE>(self.height[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u8>();
		size += size_of::<f32>();
		size
	}
}

use crate::frame::Item;

impl Item {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u16::<BE>().map(|x| self.r#type.push(x))?;
		r.read_u8().map(|x| self.state.push(x))?;
		r.read_f32::<BE>().map(|x| self.direction.push(x))?;
		self.velocity.read_append(r, version)?;
		self.position.read_append(r, version)?;
		r.read_u16::<BE>().map(|x| self.damage.push(x))?;
		r.read_f32::<BE>().map(|x| self.timer.push(x))?;
		r.read_u32::<BE>().map(|x| self.id.push(x))?;
		if version.gte(3, 2) {
			self.misc.as_mut().unwrap().read_append(r, version)?;
			if version.gte(3, 6) {
				r.read_i8().map(|x| self.owner.as_mut().unwrap().push(x))?;
				if version.gte(3, 16) {
					r.read_u16::<BE>()
						.map(|x| self.instance_id.as_mut().unwrap().push(x))?
				}
			}
		};
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u16::<BE>(self.r#type[i])?;
		w.write_u8(self.state[i])?;
		w.write_f32::<BE>(self.direction[i])?;
		self.velocity.write(w, version, i)?;
		self.position.write(w, version, i)?;
		w.write_u16::<BE>(self.damage[i])?;
		w.write_f32::<BE>(self.timer[i])?;
		w.write_u32::<BE>(self.id[i])?;
		if version.gte(3, 2) {
			self.misc.as_ref().unwrap().write(w, version, i)?;
			if version.gte(3, 6) {
				w.write_i8(self.owner.as_ref().unwrap()[i])?;
				if version.gte(3, 16) {
					w.write_u16::<BE>(self.instance_id.as_ref().unwrap()[i])?
				}
			}
		};
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u16>();
		size += size_of::<u8>();
		size += size_of::<f32>();
		size += Velocity::size(version);
		size += Position::size(version);
		size += size_of::<u16>();
		size += size_of::<f32>();
		size += size_of::<u32>();
		if version.gte(3, 2) {
			size += ItemMisc::size(version);
			if version.gte(3, 6) {
				size += size_of::<i8>();
				if version.gte(3, 16) {
					size += size_of::<u16>()
				}
			}
		};
		size
	}
}

use crate::frame::ItemMisc;

impl ItemMisc {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u8().map(|x| self.0.push(x))?;
		r.read_u8().map(|x| self.1.push(x))?;
		r.read_u8().map(|x| self.2.push(x))?;
		r.read_u8().map(|x| self.3.push(x))?;
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u8(self.0[i])?;
		w.write_u8(self.1[i])?;
		w.write_u8(self.2[i])?;
		w.write_u8(self.3[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size
	}
}

use crate::frame::Position;

impl Position {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_f32::<BE>().map(|x| self.x.push(x))?;
		r.read_f32::<BE>().map(|x| self.y.push(x))?;
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_f32::<BE>(self.x[i])?;
		w.write_f32::<BE>(self.y[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<f32>();
		size += size_of::<f32>();
		size
	}
}

use crate::frame::Post;

impl Post {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u8().map(|x| self.character.push(x))?;
		r.read_u16::<BE>().map(|x| self.state.push(x))?;
		self.position.read_append(r, version)?;
		r.read_f32::<BE>().map(|x| self.direction.push(x))?;
		r.read_f32::<BE>().map(|x| self.percent.push(x))?;
		r.read_f32::<BE>().map(|x| self.shield.push(x))?;
		r.read_u8().map(|x| self.last_attack_landed.push(x))?;
		r.read_u8().map(|x| self.combo_count.push(x))?;
		r.read_u8().map(|x| self.last_hit_by.push(x))?;
		r.read_u8().map(|x| self.stocks.push(x))?;
		if version.gte(0, 2) {
			r.read_f32::<BE>()
				.map(|x| self.state_age.as_mut().unwrap().push(x))?;
			if version.gte(2, 0) {
				self.state_flags.as_mut().unwrap().read_append(r, version)?;
				r.read_f32::<BE>()
					.map(|x| self.misc_as.as_mut().unwrap().push(x))?;
				r.read_u8()
					.map(|x| self.airborne.as_mut().unwrap().push(x))?;
				r.read_u16::<BE>()
					.map(|x| self.ground.as_mut().unwrap().push(x))?;
				r.read_u8().map(|x| self.jumps.as_mut().unwrap().push(x))?;
				r.read_u8()
					.map(|x| self.l_cancel.as_mut().unwrap().push(x))?;
				if version.gte(2, 1) {
					r.read_u8()
						.map(|x| self.hurtbox_state.as_mut().unwrap().push(x))?;
					if version.gte(3, 5) {
						self.velocities.as_mut().unwrap().read_append(r, version)?;
						if version.gte(3, 8) {
							r.read_f32::<BE>()
								.map(|x| self.hitlag.as_mut().unwrap().push(x))?;
							if version.gte(3, 11) {
								r.read_u32::<BE>()
									.map(|x| self.animation_index.as_mut().unwrap().push(x))?;
								if version.gte(3, 16) {
									r.read_u16::<BE>().map(|x| {
										self.last_hit_by_instance.as_mut().unwrap().push(x)
									})?;
									r.read_u16::<BE>()
										.map(|x| self.instance_id.as_mut().unwrap().push(x))?
								}
							}
						}
					}
				}
			}
		};
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u8(self.character[i])?;
		w.write_u16::<BE>(self.state[i])?;
		self.position.write(w, version, i)?;
		w.write_f32::<BE>(self.direction[i])?;
		w.write_f32::<BE>(self.percent[i])?;
		w.write_f32::<BE>(self.shield[i])?;
		w.write_u8(self.last_attack_landed[i])?;
		w.write_u8(self.combo_count[i])?;
		w.write_u8(self.last_hit_by[i])?;
		w.write_u8(self.stocks[i])?;
		if version.gte(0, 2) {
			w.write_f32::<BE>(self.state_age.as_ref().unwrap()[i])?;
			if version.gte(2, 0) {
				self.state_flags.as_ref().unwrap().write(w, version, i)?;
				w.write_f32::<BE>(self.misc_as.as_ref().unwrap()[i])?;
				w.write_u8(self.airborne.as_ref().unwrap()[i])?;
				w.write_u16::<BE>(self.ground.as_ref().unwrap()[i])?;
				w.write_u8(self.jumps.as_ref().unwrap()[i])?;
				w.write_u8(self.l_cancel.as_ref().unwrap()[i])?;
				if version.gte(2, 1) {
					w.write_u8(self.hurtbox_state.as_ref().unwrap()[i])?;
					if version.gte(3, 5) {
						self.velocities.as_ref().unwrap().write(w, version, i)?;
						if version.gte(3, 8) {
							w.write_f32::<BE>(self.hitlag.as_ref().unwrap()[i])?;
							if version.gte(3, 11) {
								w.write_u32::<BE>(self.animation_index.as_ref().unwrap()[i])?;
								if version.gte(3, 16) {
									w.write_u16::<BE>(
										self.last_hit_by_instance.as_ref().unwrap()[i],
									)?;
									w.write_u16::<BE>(self.instance_id.as_ref().unwrap()[i])?
								}
							}
						}
					}
				}
			}
		};
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u8>();
		size += size_of::<u16>();
		size += Position::size(version);
		size += size_of::<f32>();
		size += size_of::<f32>();
		size += size_of::<f32>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		if version.gte(0, 2) {
			size += size_of::<f32>();
			if version.gte(2, 0) {
				size += StateFlags::size(version);
				size += size_of::<f32>();
				size += size_of::<u8>();
				size += size_of::<u16>();
				size += size_of::<u8>();
				size += size_of::<u8>();
				if version.gte(2, 1) {
					size += size_of::<u8>();
					if version.gte(3, 5) {
						size += Velocities::size(version);
						if version.gte(3, 8) {
							size += size_of::<f32>();
							if version.gte(3, 11) {
								size += size_of::<u32>();
								if version.gte(3, 16) {
									size += size_of::<u16>();
									size += size_of::<u16>()
								}
							}
						}
					}
				}
			}
		};
		size
	}
}

use crate::frame::Pre;

impl Pre {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u32::<BE>().map(|x| self.random_seed.push(x))?;
		r.read_u16::<BE>().map(|x| self.state.push(x))?;
		self.position.read_append(r, version)?;
		r.read_f32::<BE>().map(|x| self.direction.push(x))?;
		self.joystick.read_append(r, version)?;
		self.cstick.read_append(r, version)?;
		r.read_f32::<BE>().map(|x| self.triggers.push(x))?;
		r.read_u32::<BE>().map(|x| self.buttons.push(x))?;
		r.read_u16::<BE>().map(|x| self.buttons_physical.push(x))?;
		self.triggers_physical.read_append(r, version)?;
		if version.gte(1, 2) {
			r.read_i8()
				.map(|x| self.raw_analog_x.as_mut().unwrap().push(x))?;
			if version.gte(1, 4) {
				r.read_f32::<BE>()
					.map(|x| self.percent.as_mut().unwrap().push(x))?;
				if version.gte(3, 15) {
					r.read_i8()
						.map(|x| self.raw_analog_y.as_mut().unwrap().push(x))?;
					if version.gte(3, 17) {
						r.read_i8()
							.map(|x| self.raw_analog_cstick_x.as_mut().unwrap().push(x))?;
						r.read_i8()
							.map(|x| self.raw_analog_cstick_y.as_mut().unwrap().push(x))?
					}
				}
			}
		};
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u32::<BE>(self.random_seed[i])?;
		w.write_u16::<BE>(self.state[i])?;
		self.position.write(w, version, i)?;
		w.write_f32::<BE>(self.direction[i])?;
		self.joystick.write(w, version, i)?;
		self.cstick.write(w, version, i)?;
		w.write_f32::<BE>(self.triggers[i])?;
		w.write_u32::<BE>(self.buttons[i])?;
		w.write_u16::<BE>(self.buttons_physical[i])?;
		self.triggers_physical.write(w, version, i)?;
		if version.gte(1, 2) {
			w.write_i8(self.raw_analog_x.as_ref().unwrap()[i])?;
			if version.gte(1, 4) {
				w.write_f32::<BE>(self.percent.as_ref().unwrap()[i])?;
				if version.gte(3, 15) {
					w.write_i8(self.raw_analog_y.as_ref().unwrap()[i])?;
					if version.gte(3, 17) {
						w.write_i8(self.raw_analog_cstick_x.as_ref().unwrap()[i])?;
						w.write_i8(self.raw_analog_cstick_y.as_ref().unwrap()[i])?
					}
				}
			}
		};
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u32>();
		size += size_of::<u16>();
		size += Position::size(version);
		size += size_of::<f32>();
		size += Position::size(version);
		size += Position::size(version);
		size += size_of::<f32>();
		size += size_of::<u32>();
		size += size_of::<u16>();
		size += TriggersPhysical::size(version);
		if version.gte(1, 2) {
			size += size_of::<i8>();
			if version.gte(1, 4) {
				size += size_of::<f32>();
				if version.gte(3, 15) {
					size += size_of::<i8>();
					if version.gte(3, 17) {
						size += size_of::<i8>();
						size += size_of::<i8>()
					}
				}
			}
		};
		size
	}
}

use crate::frame::StadiumTransformation;

impl StadiumTransformation {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u16::<BE>().map(|x| self.event.push(x))?;
		r.read_u16::<BE>().map(|x| self.r#type.push(x))?;
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u16::<BE>(self.event[i])?;
		w.write_u16::<BE>(self.r#type[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u16>();
		size += size_of::<u16>();
		size
	}
}

use crate::frame::Start;

impl Start {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u32::<BE>().map(|x| self.random_seed.push(x))?;
		if version.gte(3, 10) {
			r.read_u32::<BE>()
				.map(|x| self.scene_frame_counter.as_mut().unwrap().push(x))?
		};
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u32::<BE>(self.random_seed[i])?;
		if version.gte(3, 10) {
			w.write_u32::<BE>(self.scene_frame_counter.as_ref().unwrap()[i])?
		};
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u32>();
		if version.gte(3, 10) {
			size += size_of::<u32>()
		};
		size
	}
}

use crate::frame::StateFlags;

impl StateFlags {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_u8().map(|x| self.0.push(x))?;
		r.read_u8().map(|x| self.1.push(x))?;
		r.read_u8().map(|x| self.2.push(x))?;
		r.read_u8().map(|x| self.3.push(x))?;
		r.read_u8().map(|x| self.4.push(x))?;
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_u8(self.0[i])?;
		w.write_u8(self.1[i])?;
		w.write_u8(self.2[i])?;
		w.write_u8(self.3[i])?;
		w.write_u8(self.4[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size += size_of::<u8>();
		size
	}
}

use crate::frame::TriggersPhysical;

impl TriggersPhysical {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_f32::<BE>().map(|x| self.l.push(x))?;
		r.read_f32::<BE>().map(|x| self.r.push(x))?;
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_f32::<BE>(self.l[i])?;
		w.write_f32::<BE>(self.r[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<f32>();
		size += size_of::<f32>();
		size
	}
}

use crate::frame::Velocities;

impl Velocities {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_f32::<BE>().map(|x| self.self_x_air.push(x))?;
		r.read_f32::<BE>().map(|x| self.self_y.push(x))?;
		r.read_f32::<BE>().map(|x| self.knockback_x.push(x))?;
		r.read_f32::<BE>().map(|x| self.knockback_y.push(x))?;
		r.read_f32::<BE>().map(|x| self.self_x_ground.push(x))?;
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_f32::<BE>(self.self_x_air[i])?;
		w.write_f32::<BE>(self.self_y[i])?;
		w.write_f32::<BE>(self.knockback_x[i])?;
		w.write_f32::<BE>(self.knockback_y[i])?;
		w.write_f32::<BE>(self.self_x_ground[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<f32>();
		size += size_of::<f32>();
		size += size_of::<f32>();
		size += size_of::<f32>();
		size += size_of::<f32>();
		size
	}
}

use crate::frame::Velocity;

impl Velocity {
	pub fn read_append(&mut self, r: &mut &[u8], version: Version) -> Result<()> {
		r.read_f32::<BE>().map(|x| self.x.push(x))?;
		r.read_f32::<BE>().map(|x| self.y.push(x))?;
		self.validity.push(true);
		Ok(())
	}

	fn write<W: Write>(&self, w: &mut W, version: Version, i: usize) -> Result<()> {
		w.write_f32::<BE>(self.x[i])?;
		w.write_f32::<BE>(self.y[i])?;
		Ok(())
	}

	pub(crate) fn size(version: Version) -> usize {
		let mut size = 0usize;
		size += size_of::<f32>();
		size += size_of::<f32>();
		size
	}
}
